#! /bin/sh

############################################################################
# Copyright 2005, 2006 Peter Massuthe, Daniela Weinberg, Dennis Reinert,   #
#                      Jan Bretschneider and Christian Gierds              #
#                                                                          #
# This file is part of Fiona.                                              #
#                                                                          #
# Fiona is free software; you can redistribute it and/or modify it         #
# under the terms of the GNU General Public License as published by the    #
# Free Software Foundation; either version 2 of the License, or (at your   #
# option) any later version.                                               #
#                                                                          #
# Fiona is distributed in the hope that it will be useful, but WITHOUT     #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or    #
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for #
# more details.                                                            #
#                                                                          #
# You should have received a copy of the GNU General Public License along  #
# with Fiona; if not, write to the Free Software Foundation, Inc., 51      #
# Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.                     #
############################################################################

DIR=$testdir/sequence_suite

fiona.exe --net=$DIR/sequence3.owfn -a --graphtype=IG
result3=$?

fiona.exe --net=$DIR/sequence4.owfn -a --graphtype=IG
result4=$?

fiona.exe --net=$DIR/sequence5.owfn -a --graphtype=IG
result5=$?

fiona.exe --net=$DIR/sequence6.owfn -a --graphtype=IG
result6=$?

fiona.exe --net=$DIR/sequence7.owfn -a --graphtype=IG
result7=$?

fiona.exe --net=$DIR/sequence8.owfn -a --graphtype=IG
result8=$?

fiona.exe --net=$DIR/sequence9.owfn -a --graphtype=IG
result9=$?

fiona.exe --net=$DIR/sequence10.owfn -a --graphtype=IG
result10=$?

fiona.exe --net=$DIR/sequence11.owfn -a --graphtype=IG
result11=$?

fiona.exe --net=$DIR/sequence12.owfn -a --graphtype=IG
result12=$?

fiona.exe --net=$DIR/sequence13.owfn -a --graphtype=IG
result13=$?

fiona.exe --net=$DIR/sequence14.owfn -a --graphtype=IG
result14=$?

fiona.exe --net=$DIR/sequence15.owfn -a --graphtype=IG
result15=$?

fiona.exe --net=$DIR/sequence16.owfn -a --graphtype=IG
result16=$?

fiona.exe --net=$DIR/sequence17.owfn -a --graphtype=IG
result17=$?

fiona.exe --net=$DIR/sequence18.owfn -a --graphtype=IG
result18=$?

fiona.exe --net=$DIR/sequence19.owfn -a --graphtype=IG
result19=$?

fiona.exe --net=$DIR/sequence20.owfn -a --graphtype=IG
result20=$?

if test \( $result3 -eq 0 -a $result4 -eq 0 -a $result5 -eq 0 -a \
           $result6 -eq 0 -a $result7 -eq 0 -a $result8 -eq 0 -a \
           $result9 -eq 0 -a $result10 -eq 0 -a $result11 -eq 0 -a \
           $result12 -eq 0 -a $result13 -eq 0 -a $result14 -eq 0 -a \
           $result15 -eq 0 -a $result16 -eq 0 -a $result17 -eq 0 -a \
           $result18 -eq 0 -a $result19 -eq 0 -a $result20 -eq 0 \) -a \
	\( -f $DIR/sequence3.owfn.a.IG.png -a -f $DIR/sequence3.owfn.a.IG.out \) -a \
	\( -f $DIR/sequence4.owfn.a.IG.png -a -f $DIR/sequence4.owfn.a.IG.out \) -a \
	\( -f $DIR/sequence5.owfn.a.IG.png -a -f $DIR/sequence5.owfn.a.IG.out \) -a \
	\( -f $DIR/sequence6.owfn.a.IG.png -a -f $DIR/sequence6.owfn.a.IG.out \) -a \
	\( -f $DIR/sequence7.owfn.a.IG.png -a -f $DIR/sequence7.owfn.a.IG.out \) -a \
	\( -f $DIR/sequence8.owfn.a.IG.png -a -f $DIR/sequence8.owfn.a.IG.out \) -a \
	\( -f $DIR/sequence9.owfn.a.IG.png -a -f $DIR/sequence9.owfn.a.IG.out \) -a \
	\( -f $DIR/sequence10.owfn.a.IG.png -a -f $DIR/sequence10.owfn.a.IG.out \) -a \
	\( -f $DIR/sequence11.owfn.a.IG.png -a -f $DIR/sequence11.owfn.a.IG.out \) -a \
	\( -f $DIR/sequence12.owfn.a.IG.png -a -f $DIR/sequence12.owfn.a.IG.out \) -a \
	\( -f $DIR/sequence13.owfn.a.IG.png -a -f $DIR/sequence13.owfn.a.IG.out \) -a \
	\( -f $DIR/sequence14.owfn.a.IG.png -a -f $DIR/sequence14.owfn.a.IG.out \) -a \
	\( -f $DIR/sequence15.owfn.a.IG.png -a -f $DIR/sequence15.owfn.a.IG.out \) -a \
	\( -f $DIR/sequence16.owfn.a.IG.png -a -f $DIR/sequence16.owfn.a.IG.out \) -a \
	\( -f $DIR/sequence17.owfn.a.IG.png -a -f $DIR/sequence17.owfn.a.IG.out \) -a \
	\( -f $DIR/sequence18.owfn.a.IG.png -a -f $DIR/sequence18.owfn.a.IG.out \) -a \
	\( -f $DIR/sequence19.owfn.a.IG.png -a -f $DIR/sequence19.owfn.a.IG.out \) -a \
	\( -f $DIR/sequence20.owfn.a.IG.png -a -f $DIR/sequence20.owfn.a.IG.out \)
then
  result=0
else
  result=1
fi

exit $result
