#! /bin/bash

command="rachel -a $testdir/testfiles/purchase_order.sa -o $testdir/testfiles/purchase_order.og --noop --verbose"
echo ""
echo "test: verbosely noop"
echo "      $command"
$command &> /dev/null
