#! /bin/bash

command="rachel -a $testdir/testfiles/traveler.sa -o $testdir/testfiles/agency_airline.og -m matching -v"
echo ""
echo "test: matching (verbose)"
echo "      $command"
$command &> /dev/null
