#! /bin/bash

command="rachel -a $testdir/testfiles/traveler.sa -o $testdir/testfiles/agency_airline.og -m simulation -d"
echo ""
echo "test: simulation with Dot output"
echo "      $command"
$command &> /dev/null
