#! /bin/bash

echo ""

echo "test: matching"
echo "      rachel -a $testdir/testfiles/traveler.og -o $testdir/testfiles/agency_airline.og -m matching &> /dev/null"
rachel -a $testdir/testfiles/traveler.og -o $testdir/testfiles/agency_airline.og -m matching &> /dev/null

exit $?
