#!/usr/bin/env bash

command="rachel -a $testdir/testfiles/purchase_order.sa -o $testdir/testfiles/purchase_order.og -m matching --threshold=0.2"
echo ""
echo "test: matching with threshold 0.2"
echo "      $command"
$command &> /dev/null
