#! /bin/bash

echo ""

echo "test: version output"
echo "      rachel --version &> /dev/null"
rachel --version &> /dev/null
result1=$?

echo "test: help output"
echo "      owfn2bpel --help &> /dev/null"
rachel --help &> /dev/null
result2=$?


if [ $result1 -eq 0 -a $result2 -eq 0 ]
then
  result=0
else
  result=1
fi

exit $result
