#! /bin/bash

echo ""

echo "test: simulation"
echo "      rachel -a $testdir/testfiles/traveler.og -o $testdir/testfiles/agency_airline.og -m simulation &> /dev/null"
rachel -a $testdir/testfiles/traveler.og -o $testdir/testfiles/agency_airline.og -m simulation &> /dev/null

exit $?
