#!/usr/bin/env bash

command="rachel -a $testdir/testfiles/traveler.sa -o $testdir/testfiles/agency_airline.og -m simulation -d --png"
echo ""
echo "test: simulation with Dot output"
echo "      $command"

if test "$DOT" = "not found"; then
	# The exit 77 is the magic value which tells Automake's `make check'
	# that this test was skipped.
  exit 77
fi

$command &> /dev/null

if [ $? -eq 0 ]
	then rm $builddir/traveler.sa_agency_airline.og_simulation.dot $builddir/traveler.sa_agency_airline.og_simulation.dot.png
fi
