#! /bin/bash

command="rachel -a $testdir/testfiles/traveler.sa -o $testdir/testfiles/agency_airline.og -m simulation -d"
echo ""
echo "test: simulation with Dot output"
echo "      $command"
$command &> /dev/null

if [ $? -eq 0 ]
	then rm $builddir/traveler.sa_agency_airline.og_simulation.dot $builddir/traveler.sa_agency_airline.og_simulation.dot.png
fi
