/*
 * VisualLSCDialog.java
 *
 * Created on Oct 6, 2010, 1:38:58 PM
 */

package lscminer.gui;

import javax.swing.JDialog;
import lscminer.datastructure.LSC;

/**
 *
 * @author nacuong
 */
public class VisualLSCDialog extends javax.swing.JDialog {

    /** Creates new form VisualLSCDialog */
    public VisualLSCDialog(java.awt.Frame parent, LSC lsc) {
        super(parent, false);
        this.setResizable(false);
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        LSCGraphic lscGraphic = new LSCGraphic(lsc);
        this.getContentPane().add(lscGraphic);
        this.setResizable(false);
        this.setLocationByPlatform(true);
        this.setSize((lsc.getDistinctObjectNo()*(lscGraphic.defaultRecWidth +2)
                + (lsc.getDistinctObjectNo()-1)*lscGraphic.defaultRecDistance + 2*lscGraphic.defaultOrigCoord) ,
                lscGraphic.horLength + lscGraphic.defaultRecHeight + 2*lscGraphic.defaultOrigCoord + 20);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

}
