/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.top.lang.flowcharts.validation;


import hub.top.lang.flowcharts.DiagramArc;
import hub.top.lang.flowcharts.DiagramNode;
import hub.top.lang.flowcharts.Endnode;
import hub.top.lang.flowcharts.ResourceNode;
import hub.top.lang.flowcharts.StartNode;
import hub.top.lang.flowcharts.Subprocess;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.top.lang.flowcharts.WorkflowDiagram}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WorkflowDiagramValidator {
	boolean validate();

	boolean validateDiagramNodes(EList<DiagramNode> value);
	boolean validateStartNode(StartNode value);
	boolean validateEndNode(Endnode value);
	boolean validateProcessOutput(EList<ResourceNode> value);
	boolean validateProcessOutputOpt(EList<ResourceNode> value);
	boolean validateDiagramArcs(EList<DiagramArc> value);

	boolean validateName(String value);

  boolean validateProcessInput(EList<ResourceNode> value);

  boolean validateProcessInputOpt(EList<ResourceNode> value);

  boolean validateProcessCalls(EList<Subprocess> value);
}
