all: sara-1.10 lola-2.0-unreleased

sara-1.10: sara-1.10.tar.gz
	./install.sh sara-1.10.tar.gz

lola-2.0-unreleased: lola-2.0-unreleased.tar.gz
	./install.sh lola-2.0-unreleased.tar.gz

distclean:
	rm -fr sara-1.10 lola-2.0-unreleased
