// See the manual for a description and all possible parameters.

// NUMERICAL PARAMETERS
#define REPORTFREQUENCY 100000
#define HASHSIZE 65536
#define CAPACITY 1
#define CHECKCAPACITY

// REDUCTION TECHNIQUES
#define PREDUCTION
//#define STUBBORN

// GRAPH EXPLORATION STRATEGY
#define DEPTH_FIRST

// VERIFICATION PROBLEM
#define STATESPACE
