// See the manual for a description and all possible parameters.

// NUMERICAL PARAMETERS
#define REPORTFREQUENCY 10000
#define MAXIMALSTATES 100000
#define HASHSIZE 65536

// REDUCTION TECHNIQUES
#define PREDUCTION

// GRAPH EXPLORATION STRATEGY
#define DEPTH_FIRST

// VERIFICATION PROBLEM
#define FULL
