#! /bin/sh

echo "TEST: test_init"

echo "  [1/2] collecting test LoLA sources..."
$MAKE dist  --silent --directory=.. distdir=lola > /dev/null
tar xfz ../lola.tar.gz

echo "  [2/2] configuring LoLA..."
cd lola
./configure --silent  > /dev/null
cd ..
