#!/usr/bin/env bash

echo "TEST: test_umlprocess"

echo "  [1/3] patching LoLA..."
rm -fr lola/src/userconfig.H
cp $testdir/nets/umlprocess.userconfig.H.liveprop lola/src/userconfig.H

echo "  [2/3] compiling LoLA..."
$MAKE clean all --silent --directory=lola > /dev/null

echo "  [3/3] running LoLA..."
lola/src/lola $testdir/nets/umlprocess.lola > /dev/null

if [ $? -eq 1 ]
then
  result=0
else
  result=1
fi

exit $result
