#!/usr/bin/env bash

echo "TEST: test_planner"

echo "  [1/3] patching LoLA..."
rm -fr lola/src/userconfig.H
cp $testdir/nets/planner.userconfig.H.statepredicate lola/src/userconfig.H

echo "  [2/3] compiling LoLA..."
$MAKE clean all --silent --directory=lola > /dev/null

echo "  [3/3] running LoLA..."
lola/src/lola $testdir/nets/planner.lola -a $testdir/nets/planner.task > /dev/null

result=$?

exit $result
