#! /bin/bash

echo "TEST: test_unbounded"

echo "  [1/3] patching LoLA..."
rm -fr lola/src/userconfig.H
cp $testdir/nets/unbounded.userconfig.H.boundednet lola/src/userconfig.H

echo "  [2/3] compiling LoLA..."
make clean all --silent --directory=lola > /dev/null

echo "  [3/3] running LoLA..."
lola/src/lola $testdir/nets/unbounded.lola > /dev/null

exit $?
