#! /bin/sh

echo "TEST: test_phils"

echo "  [1/3] patching LoLA..."
rm -fr lola/src/userconfig.H
cp $testdir/nets/phils.userconfig.H.deadlock lola/src/userconfig.H

echo "  [2/3] compiling LoLA..."
$MAKE clean all --silent --directory=lola > /dev/null

echo "  [3/3] running LoLA..."
lola/src/lola $testdir/nets/phils.lola > /dev/null

exit $?
