#!/usr/bin/env bash

echo "TEST: test_limited"

echo "  [1/3] patching LoLA..."
rm -fr lola/src/userconfig.H
cp $testdir/nets/echo.userconfig.H.limited lola/src/userconfig.H

echo "  [2/3] compiling LoLA..."
$MAKE clean all --silent --directory=lola > /dev/null

echo "  [3/3] running LoLA..."
lola/src/lola $testdir/nets/echo.lola &> /dev/null

let result=$?-5

exit $result
