#! /bin/bash

echo "TEST: test_phils"

echo "  [1/3] patching LoLA..."
rm -fr lola/src/userconfig.H
cp $testdir/nets/choreography.userconfig.H.deadlock lola/src/userconfig.H

echo "  [2/3] compiling LoLA..."
make clean all --silent --directory=lola > /dev/null

echo "  [3/3] running LoLA..."
lola/src/lola $testdir/nets/choreography.lola > /dev/null

if [ $? -eq 1 ]
then
  result=0
else
  result=1
fi

exit $result
