#! /bin/sh

echo "TEST: test_process"

echo "  [1/3] patching LoLA..."
rm -fr lola/src/userconfig.H
cp $testdir/nets/process.userconfig.H.modelchecking lola/src/userconfig.H

echo "  [2/3] compiling LoLA..."
$MAKE clean all --silent --directory=lola > /dev/null

echo "  [3/3] running LoLA..."
lola/src/lola $testdir/nets/process.lola -a $testdir/nets/process.task > /dev/null

if [ $? -eq 1 ]
then
  result=0
else
  result=1
fi

exit $result