#! /bin/sh
test "${ZSH_VERSION+set}" = set && alias -g '${1+"$@"}'='"$@"'
cd '/home/jeed/workspace/cosme/tests'
exec ${CONFIG_SHELL-/bin/bash} "/home/jeed/workspace/cosme/tests/./testsuite" -v -d  6 ${1+"$@"}
exit 1
