#! /bin/bash

# This script configures and compiles LoLA given in a directory "lola".
# Therefore, it uses a the userconfig.H provided in the "src" directory.
# The generated executable is moved into the "src" directory and named "mylola".

echo [1/2] configuring LoLA...
cd lola
./configure > /dev/null

echo [2/2] compiling LoLA...
make > /dev/null
