This file provides information for building hub.top.GRETA.diagram.process.

1. download/checkout hub.top.GRETA from our repository,
   e.g. svn.gna.org/svn/service-tech/trunk/greta/hub.top.greta
   
2. download/checkout hub.top.GRETA.diagram from our repository,
   e.g. svn.gna.org/svn/service-tech/trunk/greta/hub.top.greta.diagram

3. generate the GMF Diagram Code with the GMF builder from
   hub.top.GRETA/model/adaptiveProcess.gmfgen 
   (in Eclipse, right-click on the file and choose "Generate Diagram Code")

   this generates corresponding source files in hub.top.GRETA.diagram.process
   
4. remove in hub.top.GRETA.diagram.process
   from the Java package hub.top.adaptiveSystem.diagram.edit.parts
   
   all classes that DO NOT begin with AP_
   these are:
   
   	/hub.top.GRETA.diagram.process/src/hub/top/adaptiveSystem/diagram/edit/parts/ArcToConditionEditPart.java
	/hub.top.GRETA.diagram.process/src/hub/top/adaptiveSystem/diagram/edit/parts/ArcToConditionWeightEditPart.java
	/hub.top.GRETA.diagram.process/src/hub/top/adaptiveSystem/diagram/edit/parts/ArcToEventEditPart.java
	/hub.top.GRETA.diagram.process/src/hub/top/adaptiveSystem/diagram/edit/parts/ArcToEventWeightEditPart.java
	/hub.top.GRETA.diagram.process/src/hub/top/adaptiveSystem/diagram/edit/parts/ConditionAPEditPart.java
	/hub.top.GRETA.diagram.process/src/hub/top/adaptiveSystem/diagram/edit/parts/ConditionAPNameEditPart.java
	/hub.top.GRETA.diagram.process/src/hub/top/adaptiveSystem/diagram/edit/parts/ConditionAPTempEditPart.java
	/hub.top.GRETA.diagram.process/src/hub/top/adaptiveSystem/diagram/edit/parts/ConditionAPTokenEditPart.java
	/hub.top.GRETA.diagram.process/src/hub/top/adaptiveSystem/diagram/edit/parts/EventAPEditPart.java
	/hub.top.GRETA.diagram.process/src/hub/top/adaptiveSystem/diagram/edit/parts/EventAPNameEditPart.java
	/hub.top.GRETA.diagram.process/src/hub/top/adaptiveSystem/diagram/edit/parts/EventAPTempEditPart.java
   
   
see docs/readme-dev.txt for further details and explanations.