This file provides information for building hub.top.GRETA.diagram.process.

1. download/checkout hub.top.GRETA from our repository,
   e.g. svn.gna.org/svn/service-tech/trunk/greta/hub.top.greta
   
2. download/checkout hub.top.GRETA.diagram from our repository,
   e.g. svn.gna.org/svn/service-tech/trunk/greta/hub.top.greta.diagram

3. generate the GMF Diagram Code with the GMF builder from
   hub.top.GRETA/model/adaptiveProcess.gmfgen 
   (in Eclipse, right-click on the file and choose "Generate Diagram Code")

   this generates corresponding source files in hub.top.GRETA.diagram.process
   
see docs/readme-dev.txt for further details and explanations.