/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.top.editor.ptnetLoLA.validation;

import hub.top.editor.ptnetLoLA.Annotation;
import hub.top.editor.ptnetLoLA.Arc;
import hub.top.editor.ptnetLoLA.NodeType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.top.editor.ptnetLoLA.Node}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NodeValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateAnnotation(Annotation value);
	boolean validateIncoming(EList<Arc> value);
	boolean validateOutgoing(EList<Arc> value);
	boolean validateType(NodeType value);
}
