#!/usr/bin/env python

import requests
import json
import sys

url     = "http://tools.service-technology.org"
data    = {'data': json.dumps({'tool': sys.argv[1], 'parameters': sys.argv[2:]})}
headers = {'Content-type': 'application/json'}
r = requests.post(url, data=json.dumps(data), headers=headers)

res = json.loads(r.text)

for line in res['result']['output']['stdout']:
    print line

for line in res['result']['output']['stderr']:
    print >> sys.stderr, line

sys.exit(res['result']['exit']['code'])
