// This file ‘userconfig.H.offspring’ was created by LoLA 1.11.
// To compile a binary with this configuration, copy this file into the folder
// ‘src/configs’ of the LoLA distribution and execute ‘make lola-offspring’.
// See the manual for a description and all possible parameters.

// NUMERICAL PARAMETERS
#define CAPACITY 6
#define CHECKCAPACITY
#define REPORTFREQUENCY 100000
#define HASHSIZE 65536

// REDUCTION TECHNIQUES
#define COVER
#define PREDUCTION

// GRAPH EXPLORATION STRATEGY
#define DEPTH_FIRST

// VERIFICATION PROBLEM
#define FULL
