/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class genet_LibGenet */

#ifndef _Included_genet_LibGenet
#define _Included_genet_LibGenet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     genet_LibGenet
 * Method:    genet_init
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_genet_LibGenet_genet_1init
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
