######################################################################
# Automatically generated by qmake (2.01a) Sa Jul 28 16:37:59 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gui_organizer.h ../src/helpers.h
FORMS += dialog.ui
SOURCES += bpel2owfn-gui.cc gui_organizer.cc ../src/helpers.cc
