#ifndef BPEL_ATTRIBUTES_H
#define BPEL_ATTRIBUTES_H


// generated by Kimwitu++
#include "bpel-kc-k.h" // phylum definitions
#include "bpel-kc-yystype.h" // data types for tokens and non-terminals

#include <map>


class attributeManager
{
  private:
  	/// an array to store attributenames with value
  	typedef std::map<std::string, std::string> attributeDataModel;    
    
    /// an array to store attributes of XML-elements
    std::map<unsigned int, attributeDataModel > attributeArray;
	
	/// an array to store [activities]->[atributes]->[opt?]
    std::map<unsigned int, std::map<std::string, bool> > attributeDB;
    
    /// to initialize the attributeDB
    void initAttributeDB();

    /// is attribute of activity or not
    bool isAttribute(unsigned int activity, std::string attribute);

    /// attributes of activities are optional or not
    bool isOptional(unsigned int activity, std::string attribute);

  public:
    /// constructor
    attributeManager();

    /// consecutive enumeration of XML-elements
    unsigned int nodeId;

    /// returns the value of an attribute
    kc::casestring read(kc::integer elementId, std::string attributeName);

    /// increases the id
    kc::integer nextId();

    /// defines an attribute
    void define(kc::casestring attributeName, kc::casestring attributeValue);

    /// dummy for future check-function
    void check(kc::integer elementId, unsigned int type);
};




/*
    list of default values of attributes:
    -------------------------------------
    tProcess.queryLanguage = http://www.w3.org/TR/1999/REC-xpath-19991116
            .expressionLanguage = http://www.w3.org/TR/1999/REC-xpath-19991116
            .suppressJoinFailure = no
            .enableInstanceCompensation = no
            .abstractProcess = no

    tActivity.suppressJoinFailure = no

    tCorrelation.initiate = no

    tReceive.createInstance = no

    tPick.createInstance = no

    tScope.variableAccessSerializable = no
*/

/*
    list of data types of attributes:
    ---------------------------------
    tBoolean-expr
      tActivity.joinCondition
      tSource.transitionCondition
      tCase.condition
      tWhile.condition

    tDuration-expr
      tOnAlarm.for
      tWait.for

    tDeadline-expr
      tOnAlarm.until
      tWait.until

    tBoolean (yes|no)
      tProcess.suppressJoinFailure, tProcess.enableInstanceCompensation, tProcess.abstractProcess
      tActivity.suppressJoinFailure
      tCorrelation.initiate
      tReceive.createInstance
      tFrom.opaque
      tTo.opaque
      tPick.createInstance
      tScope.variableAccessSerializable

    tRoles (myRole|partnerRole)
      tFrom.endpointReference
      tTo.endpointReference
*/

#endif
