/*
 * main.h
 *
 * Change log:
 * 
 * date        | author        | changes
 * ---------------------------------------------------------------------
 *  2005-11-09 | Gierds        | added external variable debug_level
 *
 */

#ifndef MAIN_H
#define MAIN_H

#include <cstdio>
#include <iostream>
#include <fstream>
#include <string>


#include "bpel-kc-k.h"          // generated by kimwitu++
#include "bpel-kc-rk.h"         // generated by kimwitu++
#include "bpel-kc-unpk.h"       // generated by kimwitu++
#include "bpel-unparse-xml.h"   // pretty-printers
#include "bpel-unparse-petri.h" // pretty-printers
#include "petrinet.h"           // Petri Net support
#include "debug.h"		// debugging help

/* defined by Bison */
extern int yyparse();
extern int yydebug;
extern kc::tProcess TheProcess;


/* defined by flex */
extern int yylineno;
extern char *yytext;
extern int yy_flex_debug;
extern FILE *yyin;


/// function to display error messages from lexic and syntactical analysis
int yyerror(const char* msg);

/// used to indicate trace_level
extern int debug_level;

#endif
