/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.top.editor.ptnetLoLA.validation;

import hub.top.editor.ptnetLoLA.RefMarkedPlace;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.top.editor.ptnetLoLA.Marking}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MarkingValidator {
	boolean validate();

	boolean validatePlaces(EList<RefMarkedPlace> value);
}
