/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.top.editor.ptnetLoLA.validation;

import hub.top.editor.ptnetLoLA.Annotation;
import hub.top.editor.ptnetLoLA.Arc;
import hub.top.editor.ptnetLoLA.Marking;
import hub.top.editor.ptnetLoLA.Place;
import hub.top.editor.ptnetLoLA.Transition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.top.editor.ptnetLoLA.PtNet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PtNetValidator {
	boolean validate();

	boolean validatePlaces(EList<Place> value);
	boolean validateTransitions(EList<Transition> value);
	boolean validateInitialMarking(Marking value);
	boolean validateAnnotation(Annotation value);
	boolean validateArcs(EList<Arc> value);
	boolean validateFinalMarking(Marking value);
}
