#! /bin/sh

command="bpel2owfn --input=$testdir/testfiles/purchaseOrderProcess.bpel --mode=petrinet --format=dot --output=purchaseOrderProcess"
echo ""
echo "test: Petri net file output: Dot format"
echo "      $command"
$command &> /dev/null

if [ $? -eq 0 ]
	then rm $builddir/purchaseOrderProcess.dot $builddir/purchaseOrderProcess.png
fi
