#! /bin/bash

command="bpel2owfn --input=$testdir/bpel4chor/chor_paper_traveler.bpel --input=$testdir/bpel4chor/chor_paper_airline.bpel --input=$testdir/bpel4chor/chor_paper_traveler.bpel --topology=$testdir/bpel4chor/chor_paper_topology10.xml --mode=choreography --parameter=communicationonly --output=choreography10 --format=owfn"
echo ""
echo "test: BPEL4Chor choreography with 10 instances"
echo "      $command"
$command &> /dev/null

if [ $? -eq 0 ]
	then rm $builddir/choreography10.owfn
fi
