#! /bin/bash

command="bpel2owfn --input=$testdir/consistency/coffee.bpel --input=$testdir/consistency/customer1.bpel --mode=choreography --format=lola --parameter=communicationonly --parameter=reduce --output=coffee_customer1"
echo ""
echo "test: user-defined choreography, customer 1"
echo "      $command"
$command &> /dev/null
