#! /bin/sh

command="bpel2owfn --input=$testdir/testfiles/purchaseOrderProcess.bpel --mode=petrinet --format=lola --output=purchaseOrderProcess"
echo ""
echo "test: Petri net file output: LoLA format"
echo "      $command"
$command &> /dev/null

if [ $? -eq 0 ]
	then rm $builddir/purchaseOrderProcess.lola $builddir/purchaseOrderProcess.task
fi
