#!/usr/bin/env bash

command="bpel2owfn -mcfg --input=$testdir/sa_tests/sa00087.bpel" # --wsdl=$testdir/sa_tests/sa00087.wsdl"
echo ""
echo "test: static analysis test [SA00087]"
echo "      $command"
$command &> /dev/null
