#! /bin/bash

#############################################################################
# Copyright 2005, 2006 Niels Lohmann, Christian Gierds                      #
#                                                                           #
# This file is part of GNU BPEL2oWFN.                                       #
#                                                                           #
# GNU BPEL2oWFN is free software; you can redistribute it and/or modify it  #
# under the terms of the GNU General Public License as published by the     #
# Free Software Foundation; either version 2 of the License, or (at your    #
# option) any later version.                                                #
#                                                                           #
# GNU BPEL2oWFN is distributed in the hope that it will be useful, but      #
# WITHOUT ANY WARRANTY; without even the implied warranty of                #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General  #
# Public License for more details.                                          #
#                                                                           #
# You should have received a copy of the GNU General Public License along   #
# with GNU BPEL2oWFN; see file COPYING. if not, write to the Free Software  #
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA. #
#############################################################################

# File last changed $Date: 2007/05/17 11:43:00 $ by $Author: nielslohmann $.
# Version $Revision: 1.1 $

echo ""

echo "test: BPEL4Chor"
bpel2owfn --input=$testdir/bpel4chor/chor_paper_traveler.bpel --input=$testdir/bpel4chor/chor_paper_airline.bpel --input=$testdir/bpel4chor/chor_paper_traveler.bpel --choreography=$testdir/bpel4chor/chor_paper_topology.xml --mode=consistency --parameter=communicationonly --output=choreography --format=owfn &> /dev/null
result1=$?

if test \( $result1 -eq 0 \) -a \( -f choreography.owfn \)
then
  result=0
else
  result=1
fi

exit $result
