#! /bin/bash

#############################################################################
# GNU BPEL2oWFN -- Translating BPEL Processes into Petri Net Models
#
# Copyright (C) 2006, 2007  Niels Lohmann,
#                           Christian Gierds, and
#                           Martin Znamirowski
# Copyright (C) 2005        Niels Lohmann and
#			    Christian Gierds
#
# GNU BPEL2oWFN is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option) any
# later version.
#
# GNU BPEL2oWFN is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# GNU BPEL2oWFN; if not, see http://www.gnu.org/licenses or write to the Free
# Software Foundation,Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301  USA.
#############################################################################

# File last changed $Date: 2007/06/28 07:38:18 $ by $Author: nielslohmann $.
# Version $Revision: 1.14 $

echo ""

echo "test: Petri net file output: oWFN format"
bpel2owfn --input=$testdir/testfiles/auctionService.bpel --mode=petrinet --format=owfn --output=auctionService &> /dev/null
result1=$?

echo "test: Petri net file output: LoLA format"
bpel2owfn --input=$testdir/testfiles/loanApprovalProcess.bpel --mode=petrinet --format=lola --output=loanApprovalProcess &> /dev/null
result2=$?

echo "test: Petri net file output: dot format"
bpel2owfn --input=$testdir/testfiles/purchaseOrderProcess.bpel --mode=petrinet --parameter=reduce --format=dot --output=purchaseOrderProcess &> /dev/null
result3=$?

echo "test: pretty-printed BPEL export"
bpel2owfn --input=$testdir/testfiles/shippingService.bpel --mode=pretty -fxml --output=shippingService  &> /dev/null
result4=$?

if test \( $result1 -eq 0 -a $result2 -eq 0 -a $result3 -eq 0 -a $result4 -eq 0 \) -a \
       	\( -f auctionService.owfn -a -f loanApprovalProcess.lola -a -f purchaseOrderProcess.dot -a -f shippingService.xml \)
then 
  result=0
else
  result=1
fi

exit $result
