#!/usr/bin/env bash

command="bpel2owfn --input=$testdir/testfiles/shippingService.bpel"
echo ""
echo "test: reading WS-BPEL 2.0 abstract process (shippingService)"
echo "      $command"
$command &> /dev/null
