#! /bin/sh

#############################################################################
# Copyright 2005, 2006 Niels Lohmann                                        #
#                                                                           #
# This file is part of GNU BPEL2oWFN.                                       #
#                                                                           #
# GNU BPEL2oWFN is free software; you can redistribute it and/or modify it  #
# under the terms of the GNU General Public License as published by the     #
# Free Software Foundation; either version 2 of the License, or (at your    #
# option) any later version.                                                #
#                                                                           #
# GNU BPEL2oWFN is distributed in the hope that it will be useful, but      #
# WITHOUT ANY WARRANTY; without even the implied warranty of                #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General  #
# Public License for more details.                                          #
#                                                                           #
# You should have received a copy of the GNU General Public License along   #
# with GNU BPEL2oWFN; see file COPYING. if not, write to the Free Software  #
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA. #
#############################################################################

# File last changed $Date: 2006/12/15 19:06:42 $ by $Author: nielslohmann $.
# Version $Revision: 1.9 $

echo ""

echo "test: parser"
bpel2owfn --input=$testdir/testfiles/loan.bpel &> /dev/null
result1=$?

echo "test: XML creation"
bpel2owfn --input=$testdir/testfiles/purchase.bpel --mode=pretty -fxml --output=purchase  &> /dev/null
result2=$?

if test \( $result1 -eq 0 -a $result2 -eq 0 \) -a \
	\( -f purchase.xml \)
then
  result=0
else
  result=1
fi

exit $result
