#! /bin/sh

#############################################################################
# Copyright 2005, 2006, 2007 Niels Lohmann                                  #
#                                                                           #
# This file is part of GNU BPEL2oWFN.                                       #
#                                                                           #
# GNU BPEL2oWFN is free software; you can redistribute it and/or modify it  #
# under the terms of the GNU General Public License as published by the     #
# Free Software Foundation; either version 2 of the License, or (at your    #
# option) any later version.                                                #
#                                                                           #
# GNU BPEL2oWFN is distributed in the hope that it will be useful, but      #
# WITHOUT ANY WARRANTY; without even the implied warranty of                #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General  #
# Public License for more details.                                          #
#                                                                           #
# You should have received a copy of the GNU General Public License along   #
# with GNU BPEL2oWFN; see file COPYING. if not, write to the Free Software  #
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA. #
#############################################################################

# File last changed $Date: 2007/04/19 14:10:59 $ by $Author: nielslohmann $.
# Version $Revision: 1.9 $

echo ""

echo "test: version output"
bpel2owfn --version &> /dev/null
result1=$?

echo "test: help output"
bpel2owfn --help &> /dev/null
result2=$?

echo "test: file input"
bpel2owfn --input $testdir/testfiles/error.bpel &> /dev/null
result3=$?

echo "test: pipe input"
echo "<process>" | bpel2owfn &> /dev/null
result4=$?

if [ $result1 -eq 0 -a $result2 -eq 0 -a $result3 -eq 1 -a $result4 -eq 1 ]
then
  result=0
else
  result=1
fi

exit $result
