\input texinfo
@setfilename bpel2owfn.info
@include version.texi
@afourpaper
@finalout
@settitle GNU BPEL2oWFN User's Manual

@c ----------------------------------------------------------------------------

@copying

@b{About this document:}

This manual is for GNU BPEL2oWFN, version @value{VERSION}, a tool translating
a @acronym{BPEL} process into an open workflow net (@acronym{oWFN}), last
updated @value{UPDATED}.

Copyright @copyright{} 2005, 2006, 2007 Niels Lohmann

@quotation
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.2 or any later version
published by the Free Software Foundation; with no Invariant Sections, with the
Front-Cover Texts being ``A GNU Manual,'' and with the Back-Cover Texts as in
(a) below.  A copy of the license is included in the section entitled ``GNU Free
Documentation License.''

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.''
@end quotation

This manual does not explain how to setup or install GNU BPEL2oWFN. For this
information please read the @i{Installation Manual} which is part of the
distribution, or can be downloaded from the website of GNU BPEL2oWFN,
@url{http://www.gnu.org/software/bpel2owfn}.
@*
@iftex
@center @image{images/tools4bpel,,0.4in}
@end iftex
@ifhtml
@image{images/tools4bpel}
@end ifhtml
@*
GNU BPEL2oWFN was developed during the Tools4@acronym{BPEL} project funded by
the German Federal Ministry for Education and Research (@acronym{BMBF}), see
@url{http://www.informatik.hu-berlin.de/top/tools4bpel} for details.
@end copying

@c ----------------------------------------------------------------------------

@titlepage
@iftex
@title @image{images/bpel2owfn,,0.5in}
@end iftex

@ifnottex
@title GNU BPEL2oWFN
@end ifnottex

@subtitle Translating BPEL Processes into Open Workflow Nets
@subtitle GNU BPEL2oWFN Version @value{VERSION}, @value{UPDATED}
@vskip 4pt
@subtitle User's Manual

@author Niels Lohmann

@page


@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c ----------------------------------------------------------------------------

@ifnottex
@node Top
@top GNU BPEL2oWFN
@insertcopying
@end ifnottex

@c ----------------------------------------------------------------------------

@c * Overview:: What BPEL2oWFN can do.
@c * Petri Net Patterns:: Which patterns are implemented.
@c * Petri Net-related Functions:: What is done with the Petri net.
@c * Future Work:: What BPEL2oWFN will do in the future.
@c * References:: Bibliography of cited literature.

@menu
* Introducing BPEL2oWFN:: Introducing BPEL2oWFN.
* Invoking BPEL2oWFN:: How to invoke BPEL2oWFN.
* Warnings and Error Messages:: Warnings and Error Messages.
* File Formats:: Which file formats are supported.
* FAQ and Known Bugs:: What BPEL2oWFN cannot do, and why.
* GNU Free Documentation License::The license of this manual.
@end menu

@c ----------------------------------------------------------------------------

@contents
@paragraphindent none





@c ----------------------------------------------------------------------------

@ignore

@node Overview
@chapter Overview

@section Introduction

The Web Service Business Process Execution Language @acronym{WS-BPEL}, or @acronym{BPEL} for short, is the de-facto standard to describe orchestrations of Web services. @acronym{BPEL} is described in a plain-text specification, standardized by @acronym{OASIS, Organization for the Advancement of Structured Information Standards}, that is, it only has an informal semantics. However, to allow for computer-aided verification, a formal semantics is required.

Stahl in [Sta05] proposes a Petri net semantics that consists of a collection of Petri net patterns, one Petri net pattern for each @acronym{BPEL} construct. To translate a @acronym{BPEL} process to a Petri net model, each activity is translated with its corresponding Petri net pattern which are then composed. This semantics was overworked and adapted to @acronym{WS-BPEL} 2.0 in [Loh07], and is implemented in BPEL2oWFN.

@iftex
@image{images/toolchain,,0.7in}
@end iftex
@ifhtml
@image{images/toolchain}
@end ifhtml

BPEL2oWFN is a compiler translating a @acronym{BPEL} process into an @acronym{oWFN, open Workflow Net}, that is, into a Petri net model. This @acronym{oWFN} can then be used to:

@itemize
@item check @i{controllability} of this @acronym{oWFN}, that is, whether it is possible to properly interact with the web service,
@item generate the @i{operating guideline} of this @acronym{oWFN}, that is, a characterization of all properly interacting strategies of the web service,
@item check for deadlocks, or
@item check any temporal logic formula with several model checking tools [LoLA, MCK].
@end itemize

BPEL2oWFN uses static analysis to make the generated @acronym{oWFN}
as compact as possible to analyze a chosen property. This is called
@i{flexible model generation}.

BPEL2oWFN is the successor from @acronym{BPEL2PN} [SHS05], a
Java-based compiler generating low-level Petri nets. BPEL2oWFN can be
understood as a re-implementation for extensibility and performance issues. Its
functionality is a superset of the functionality of @acronym{BPEL2PN}.

BPEL2oWFN was written by Niels Lohmann and Christian Gierds. It is part of
the Tools4@acronym{BPEL} project funded by the German Bundesministerium f@"ur
Bildung und Forschung. See
@url{http://www.informatik.hu-berlin.de/top/tools4bpel} for details.



@section Translation Process

The translation process of the @acronym{BPEL} business process is performed in
six steps which we describe briefly in this section:

@enumerate
@item @b{Lexical and syntactical analysis}. BPEL2oWFN parses the
input process according to the specification of @acronym{BPEL4WS} version 1.1
[ACD@math{^+}03]. All information about the process is collected in a symbol
table for further use.

@item @b{Semantic analysis}. The input file is checked against the constraints
of the specification, e.g.@: that each defined link has to be used as source and
target exactly once. @acronym{BPEL} processes violating these constraints are
rejected.

@item @b{@acronym{AST} generation}. For further analysis steps the exact syntax
(indentation etc.) is not used any more. The input process is represented as
an @acronym{AST, abstract syntax tree}. While generating the @acronym{AST}, the
implicit transformation rules of @acronym{BPEL} (e.g.@: the presence of an
@samp{otherwise}-branch with an empty activity) are applied.

@item @b{Net generation}. The nodes of the @acronym{AST} are used to create
the Petri net using the pattern database by applying `unparse'-rules (rules
associating each node with a pattern).

@item @b{Net optimization} (optional). To reduce the generated net several
structural reduction rules can be applied, e.g.@: to merge sequences.

@item @b{Net output}. The generated Petri net can be exported in several file
formats.
@end enumerate



@section Concepts of BPEL2oWFN

In this section we describe the main concepts of BPEL2oWFN used to
realize the translation. Reading this section is not necessary for using
BPEL2oWFN, yet knowing the underlying algorithms and data structures
not only helps to locate bugs, but also helps you to customize
BPEL2oWFN or request a feature.

@anchor{Abstract Syntax Tree}
@subsection Abstract Syntax Tree

The @acronym{AST, abstract syntax tree} is an abstraction of the
syntax tree generated while parsing the @acronym{BPEL} process: any
unnecessary information (e.g.@: indention, brackets or other
``syntax-supporting'' elements) is omitted. It is the central data
structure of BPEL2oWFN. The nodes of the @acronym{AST} are
annotated with pointers to symbol table entries during the analysis steps.
These annotations are used to select the most compact Petri net pattern
from the pattern database to check a given property.


@anchor{Pattern Repository}
@subsection Pattern Repository

The idea of flexible model generation is to find the most compact
model to check a given property. The patterns of the Petri net
semantics of [Sta05] are designed to fit in any given context.
However when the context is known some behavior modeled in the
patterns (i.e.@: some of the nodes) can be safely removed without
changing its semantics. BPEL2oWFN is designed to hold
several sets of Petri net patterns each suitable in certain
contexts. These patterns are collected in a pattern repository.


@anchor{Petri Net API}
@subsection Petri Net API

BPEL2oWFN provides many algorithms and data structures to
build, represent, modify and simplify Petri nets and open workflow
nets, resp.@: They are the interface between the pattern database and
the file output for the model checking tool. The functions are
collected in an extensible @acronym{API, application programming interface}
allowing to add more output file
formats, structural simplification rules (optimized to preserve certain
properties such as deadlock freedom or liveness) or abstractions
(e.g.@:, abstraction from variables, abstraction from external behavior).


@anchor{Control Flow Graph}
@subsection Control Flow Graph

Beside the dynamic analysis of the generated Petri net model with Fiona
or classical model checking tools, BPEL2oWFN prototypically
implements a control flow graph (@acronym{CFG}) (cf.@: [Hei03]). This @acronym{CFG} can
be used to check most of the constraints of the specification statically,
i.e.@: without actually deploying and running the BPEL process. For example,
the @acronym{CFG} can be used to check if each variable is initialized by an
incoming message or an @code{<assign>} activity.

@end ignore





@c ----------------------------------------------------------------------------

@node Introducing BPEL2oWFN
@chapter Introducing BPEL2oWFN

BPEL2oWFN translates a web service expressed in @acronym{WS-BPEL, Web Service Business Process Execution Language}
into an oWFN (open Workflow Net). This oWFN can be used to:

@itemize
@item check for @i{controllability} or generate the @i{operating guideline} using the tool Fiona@footnote{Fiona is available at @url{http://www.informatik.hu-berlin.de/top/tools4bpel}.},
@item check for deadlocks or any other Petri net property, or
@item check any temporal logic formula with a variety of model checking tools.
@end itemize
@*

@iftex
@center @image{images/diagram,,2in}
@end iftex
@ifhtml
@center @image{images/diagram}
@end ifhtml

@*

BPEL2oWFN uses static analysis to make the generated Petri net model as compact
as possible to analyze a chosen property. This is called @i{flexible model generation}.
Furthermore, several design flaws can be detected using control and data flow analysis.

BPEL2oWFN was written by Niels Lohmann, Christian Gierds and Martin Znamirowski.
It is part of the Tools4BPEL project funded by the Bundesministerium für Bildung und
Forschung. See @url{http://www.informatik.hu-berlin.de/top/tools4bpel} for details.


@section Concepts of BPEL2oWFN

@multitable @columnfractions .28 .72

@item @b{Input BPEL Process} @tab
BPEL2oWFN can read @acronym{BPEL} processes compliant to the @acronym{WS-BPEL 2.0}
or the @acronym{BPEL4WS} 1.1 specification.

@item @b{Abstract Syntax Tree} @tab
The @acronym{AST, abstract syntax tree} is the main data structure of BPEL2oWFN.
The @acronym{AST} is annotated with information gained by static analysis.

@item @b{Control/Data Flow Graph} @tab
From the abstract syntax tree, a control/data flow graph is built. This graph
is used to apply static analysis algorithms to gain information
(e.g., dead code) about the process. These algorithms Furthermore, design
flaws such as cyclic control links or conflicting receiving activities are
detected.

@item @b{Petri Net API} @tab
The annotated abstract syntax tree is used to generate a Petri net model of the
@acronym{BPEL} process. All Petri net-related functions (adding, removing and
merging of nodes; structural reduction) are provided by the Petri net
@acronym{API, application programming interface}.

@item @b{Pattern Repository} @tab
For each @acronym{BPEL} construct, several patterns with different degrees of
abstraction are stored in the pattern repository. Using the information gained
by static analysis, the most abstract pattern applicable is used.

@item @b{Output Petri Net} @tab
The generated Petri net model can be exported to many file formats, such as
@acronym{PNML}, @acronym{LoLA}, Fiona @acronym{oWFN}, @acronym{INA}, @acronym{APNN}, or @acronym{PEP}.

@end multitable







@c ----------------------------------------------------------------------------

@node Invoking BPEL2oWFN
@chapter Invoking BPEL2oWFN

The standard invocation of BPEL2oWFN is:

@example
bpel2owfn -i service.bpel -f owfn -o
@end example

where @file{service.bpel} is a @acronym{BPEL} process. The option
@samp{-f owfn} causes BPEL2oWFN to generate an open workflow net. This
net is written to a file named @file{service.owfn}, because of the option
@samp{-o}.

BPEL2oWFN can be called without any parameter. In this case, it acts
as a simple parser for @acronym{BPEL} processes that reads its input from the
standard input (@code{stdin}).





@section Options

BPEL2oWFN supports the following command-line options:

@table @samp
@item --help
@itemx -h
Print an overview of the command-line options and exit.

@item --version
@itemx -v
Print version information and exit.

@item --input=@var{filename}.bpel
@itemx -i @var{filename}.bpel
Read a @acronym{BPEL} process from file @file{@var{filename}.bpel}.
If this parameter is omitted, input is read from standard input
(@code{stdin}).

@item --output[=@var{filename}]
@itemx -o
The generated output is written to a file called @var{filename}. If the short
form is used or the @var{filename} is omitted, the input file name is taken and
extended by the suffix of the chosen file format(s). If this parameter is
omitted, the output is passed to the standard output (@code{stdout}).

@item --log[=@var{filename}]
@itemx -l
All additional information like warnings and processing information are
written to a file called @var{filename}. If the short form is used or the
@var{filename} is omitted, the output file name is taken and extended by the
suffix @samp{.log}. If this parameter is omitted, the information is passed to
the standard error output (@code{stderr}).

@item --debug=1-4 | flex | bison
@itemx -d 1-4 | flex | bison
This option triggers different debug levels, and can enable additional
information from Flex and Bison about how the input is lexed and parsed.

Debug level:
@table @samp
@itemx 0
When errors are found, only display the error code and skip additional
information.
@itemx 1
No debug information, but display warning and error messages.
@itemx 2
All messages from @samp{-d1}. Additionally, information about the current
steps is displayed.
@itemx 3
All messages from @samp{-d2}. Additionally, the structure of the process is
shown, i.e. when a Petri net is generated...
@itemx 4
All messages from @samp{-d3}. Additionally, a message is displayed each time a
function is entered or left.
@itemx flex
Displays messages from Flex. Can be combined with any other debug level.
@itemx bison
Displays messages from Bison. Can be combined with any other debug level.
@end table


@item --reduce=0-5
@itemx -r 0-5
Apply several structural reduction rules to the generated Petri net model
(implies mode @samp{petrinet} or @samp{consistency}). The rules preserve
deadlocks, livelocks and all deadlock-free communicating partners. The rules
are organized in reduction levels:

@table @samp
@itemx 0
No rules are applied (standard).
@itemx 1
Structural dead nodes are removed; that is, unmarked places with empty preset
and transitions with a dead place in its preset are removed.
@itemx 2
All reduction rules from @samp{-r1}. Additionally, unnecessary status places
are removed. A status place is considered unnecessary if it has no outgoing
arcs.
@itemx 3
All reduction rules from @samp{-r2}. Additionally, identical nodes are merged.
Two nodes are considered identical if their presets and postsets are equal:

@iftex
@center @image{images/rb1,,1.0in} @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @image{images/rb2,,1.0in}
@end iftex
@ifhtml
@center @image{images/rb1} @image{images/rb2}
@end ifhtml


@itemx 4
All reduction rules from @samp{-r3}. Additionally, remove serial nodes:

@iftex
@center @image{images/ra1,,1.0in} @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @image{images/ra2,,1.0in}
@end iftex
@ifhtml
@center @image{images/ra1} @image{images/ra2}
@end ifhtml

@itemx 5
All reduction rules from @samp{-r4}. Additionally, remove self-loop nodes.
@end table

@end table





@subsection Modes

When invoking BPEL2oWFN several modes are possible.

@table @samp
@item --mode=@var{modus}
@itemx -m @var{modus}

BPEL2oWFN supports different modes for handling input @acronym{BPEL}
files: @samp{@var{modus}} can be one of the following:

@table @samp
@item ast

Outputs the @acronym{AST, abstract syntax tree} generated while
parsing the input file to standard output. This option is mostly
used for debugging reasons since it shows the implicit transformations
and the phylum names used when generating the Petri net.

@item cfg

For control flow analysis (a form of static analysis) a @acronym{CFG, Control
Flow Graph} is generated. It can be printed in graphical (dot)
representation. With the @acronym{CFG}, several design flaws of @acronym{BPEL}
processes such as cyclic control links or read access to uninitialized
variables can be detected statically. Furthermore, faulty constellations such
as conflicting receiving activities can be found using the @samp{cfg} mode.

@item consistency

The @samp{consistency} mode is an extension of the @samp{petrinet} mode. In the
consistency mode, several @acronym{BPEL} processes can be parsed, and a Petri
net model of their composition is generated.

The @samp{consistency} mode is in beta stage. It is not fully tested.
For examples, check the @file{test5} test script in the @file{tests} directory.
When combined with @acronym{LoLA} file output, an additional @file{.task} file
is generated. With the help of this file @acronym{LoLA} can check for weak
termination of the composition.

@item petrinet

Generates a Petri net representing the semantics of the given
process. Other options can be added to simplify or modify that generated Petri
net (see below).

@item pretty

Outputs the parsed @acronym{BPEL} file in @acronym{XML} representation. This
option is mostly used for debugging reasons as it shows the implicit
transformations and the identifiers of the @acronym{BPEL} constructs.
@end table

At most one mode can be selected. If no mode is given, BPEL2oWFN acts like
a plain @acronym{BPEL} parser; that is, the input file is read, but no output
is generated.

@end table





@subsection Additional parameters

These options control some Petri net-related options.

@table @samp
@item --parameter=@var{par}
@itemx -p @var{par}

@table @samp
@item communicationonly

Only the communicational behavior of the input @acronym{BPEL} process is
modeled. That is, the negative control flow (fault, termination, or compensation handlers, as well as @code{<exit>}, @code{<throw>}, @code{<compensate>}, @code{<compensateScope>} activities) is not translated to
the Petri net model. When combined with @samp{reduce}, this parameter yields
the most compact Petri net model.

@item fhfaults

Confines the @samp{standardfaults} parameter: in the negative control flow
(in activities in fault handlers), no further @acronym{BPEL} standard faults
can occur.

@item nointerface

When creating a @file{.dot} file, no interface is printed.

@item reduce

Apply all implemented structural reduction rules. This parameter is a shortcut
for @samp{-r5} and overrides any other defined reduction level.

@item standardfaults

Model the occurrence of standard faults. When this parameter is ommited, only
user-defined faults, that is, faults thrown with @code{<throw>} activities, and
join failures can occur. With the @samp{standardfaults} parameter, also the
occurrence of other @acronym{BPEL} standard faults is modeled. This parameter
yields the most-detailled, and thus biggest Petri net model.

@item variables

Add places for the variables of the input @acronym{BPEL} process to the Petri
net model. As the generated model abstracts from data, that is, a low-level
Petri net is generated, the @samp{variables} parameter also does not introduce
data aspects. Thus, this mode is experimental.
@end table

If you want to enable more than one parameter you have to add @samp{-p}/
@samp{--parameter} to each parameter.

@end table





@subsection Output formats

Especially for the Petri net mode, a variaty of output formats are supported. There are invoked by the
following option:

@table @samp

@item --format=@var{fileformat}
@itemx -f @var{fileformat}

Creates a file in a given ouput file format. Each file format is only available in
certain modes. If you want to use more than one output file format you have to add @samp{-f}/
@samp{--format} to each file format. Please note that the underlying modes
of the given file formats are the same. You cannot, for example, create @acronym{XML} and
@acronym{LoLA} files together since @acronym{XML} requires the mode
@samp{pretty}, whereas @acronym{LoLA} requires the mode @samp{petrinet}.

@table @asis
@item Petri net file formats (imply mode @samp{petrinet} or @samp{consistency}):

@table @samp
@item apnn
Outputs the inner of the generated open workflow net in
@acronym{APNN, Abstract Petri Net Notation}. When the parameter @samp{-o} is
used, a file with the suffix @samp{.apnn} is created.

@item ina
Outputs the inner of the generated open workflow net as untimed low-level
Petri net in @acronym{INA, Integrated Net Analyzer} format. When the parameter
@samp{-o} is used, a file with the suffix @samp{.pnt} is created.

@item lola
Outputs the inner of the generated open workflow net as low-level Petri net in
@acronym{LoLA, Low-Level Analyzer} file format. When the parameter @samp{-o}
is used, a file with the suffix @samp{.lola} is created.

@item owfn
Outputs the generated open workflow net in Fiona file format. Note that the
Fiona file format is --- together with the @acronym{PNML} file format --- the
only Petri net output format that outputs the complete open workflow net, that
is, also the interface is exported. When the parameter @samp{-o} is used, a
file with the suffix @samp{.owfn} is created.

@item pep
Outputs the inner of the generated open workflow net as low-level Petri net in
low-level @acronym{PEP} notation. When the parameter @samp{-o} is used, a
file with the suffix @samp{.llnet} is created.

@item pnml
Outputs the generated open workflow net in @acronym{PNML, Petri Net Markup
Language}. Note that the @acronym{PNML} file format is --- together with the
Fiona file format --- the only Petri net output format that outputs the
complete open workflow net, that is, also the interface is exported.
Currently, the interface places are annotated using a @code{<type>} tag
which is only supported by Yasper@footnote{Yasper is available at @url{http://www.yasper.org}.}. When the parameter @samp{-o} is used, a
file with the suffix @samp{.pnml} is created.

@item spin
Outputs the inner of the generated open workflow net as low-level Petri net in
Promela (Process Meta Language) for the model checker SPIN. When the parameter
@samp{-o} is used, a file with the suffix @samp{.spin} is created.
@end table

@item Other file formats (note the required mode):
@table @samp
@item dot
When mode @samp{petrinet} is used, the generated open workflow net is printed
in Graphviz dot representation. When mode @samp{ast} is used, the
@acronym{AST, abstract syntax tree} is printed in Graphviz dot representation.
When mode @samp{cfg} is used, the @acronym{CFG, control flow graph} is printed
in Graphviz dot representation.

In any case, when the tool @code{dot} is found in the search path during
configuration of BPEL2oWFN and the parameter @samp{-o} is used,
@code{dot} is used to generate a @acronym{PNG, Portable Network Image} file.
In this case, two files with the suffixes @samp{.dot} and @samp{.png} are
created. Note that when the @samp{ast} mode is used with the @samp{dot} file
format, the @samp{-o} parameter has to be used.

@item info
When mode @samp{petrinet} is used, information about the places and
transitions of the generated net in a
proprietary @acronym{ASCII}-based format. For each place and transition, all
roles, that is, inscriptions of the Petri net patterns, are listed. The
information can be used to correlate the generated Petri net model with the
input @acronym{BPEL} process. When the parameter @samp{-o} is used, a file
with the suffix @samp{.info} is created.

@item xml
When the mode @samp{pretty} is used, the pretty-printed input @acronym{BPEL}
process --- with the implicit transformation rules applied -- exported in
@acronym{XML, Extensible Markup Lanuage}. When the parameter @samp{-o} is
used, a file with the suffix @samp{.xml} is created.
@end table
@end table
@end table





@anchor{Examples}
@section Examples
In this section we show some examples how BPEL2oWFN can be
invoked.

@table @samp
@item bpel2owfn -i sample.bpel -flola -finfo -o -p reduce

Reads the file @file{sample.bpel}, generates a structural reduced
low-level Petri net and saves it in a @acronym{LoLA} file
@file{sample.lola}. For further information a file
@file{sample.info} is generated.

@item bpel2owfn -i sample.bpel -fowfn -d3 -o

Reads the file @file{sample.bpel}, generates a low-level open
workflow net and saves it in an @acronym{oWFN} file
@file{sample.owfn}. For further information a file
@file{sample.info} is generated. During the conversion several debug
messages are printed to standard output.

@item @var{prog} | bpel2owfn -fdot -m petrinet | dot -Tps -osample.ps

Runs the program @var{prog} and reads its output as @acronym{BPEL}
process, generates a Petri net and outputs its Graphviz dot representation.
This stream is read by @code{dot} which layouts the Petri net and creates an output
PostScript file @file{sample.ps}.

@item bpel2owfn -i sample.bpel -m ast

Reads the file @file{sample.bpel} and prints the abstract syntax tree
(@acronym{AST}) to standard output.

@item bpel2owfn -m consistency -i service1.bpel -i service2.bpel -f lola -o

Reads the files @file{service1.bpel} and @file{service2.bpel} and creates
a Petri net model of their composition. The result is written to the
@acronym{LoLA} file @file{service1_service2.lola}. Furthermore, an analysis
file @file{service1_service2.task} is written that can be processed by
@acronym{LoLA}.
@end table





@c ----------------------------------------------------------------------------
@node Warnings and Error Messages
@chapter Warnings and Error Messages

BPEL2oWFN performs several analysis steps on the input @acronym{BPEL} process.
These messages are displayed during parsing and postprocessing of the process,
and can be classified as follows:

@itemize
@item @b{Notices} do not report errors, but just give information about the
translation process.

@item @b{Syntax error messages} report problems during the lexical or
syntactical analysis of the process. See @ref{FAQ and Known Bugs} for
information about handling syntax errors.

@item @b{Static analysis messages} occur when a test described in the @acronym{WS-BPEL}
specification detects an error in the process. When such an error is found, a
@acronym{WS-BPEL} processor must reject the process. If the process is an
abstract process, the static analysis errors can be considered as warnings
as abstract processes are not meant to be executed.

@item @b{Warnings} report potential problems in the input process. The warned
problem should be corrected to assure executability of the input process.

@item @b{Errors} report problems that are explicitly mentioned in the
@acronym{WS-BPEL} specification. They should be corrected to avoid runtime
errors. Furthermore, problems can arise during the generation of a Petri net
model.

@item @b{Critical errors} make a further processing of the input process
impossible and terminate GNU BPEL2oWFN immediately.
@end itemize

An example for a message is this:

@smallexample
CubeManagement.bpel:566 - [W00114]
variable `waitResponse' used as `variable' in <from> might be uninitialized
@end smallexample

The first line contains the filename of the input process
@file{CubeManagement.bpel} and the line number @samp{566} of the displayed issue.
The line number might be imprecise; that is, it might deviate up or down a
few lines. After the line number, the error code is displayed.
@samp{W00114} stands for a warning with code 114. Further details can be
taken from the table below.

@multitable @columnfractions .05 .18 .72
@headitem Code @tab Type @tab Description

@item 6 @tab static analysis @tab
The @code{<rethrow>} activity MUST only be used within a faultHandler (i.e.
@code{<catch>} and @code{<catchAll>} elements).@footnote{The descriptions for
static analysis messages are taken from Appendix B of the @acronym{WS-BPEL}
specification.}

@item 7 @tab static analysis @tab
The @code{<compensateScope>} activity MUST only be used from within a
@code{faultHandler}, another @code{compensationHandler}, or a
@code{terminationHandler}.

@item 8 @tab static analysis @tab
The @code{<compensate>} activity MUST only be used from within a
@code{faultHandler}, another @code{compensationHandler}, or a
@code{terminationHandler}.

@item 15 @tab static analysis @tab
To be instantiated, an executable business process MUST contain at least one
@code{<receive>} or @code{<pick>} activity annotated with a
@code{createInstance="yes"} attribute.

@item 16 @tab static analysis @tab
A @code{partnerLink} MUST specify the @code{myRole} or the @code{partnerRole},
or both.

@item 17 @tab static analysis @tab
The @code{initializePartnerRole} attribute MUST NOT be used on a partnerLink
that does not have a partner role.

@item 18 @tab static analysis @tab
The name of a @code{partnerLink} MUST be unique among the names of all
partnerLinks defined within the same immediately enclosing scope.

@item 23 @tab static analysis @tab
The name of a variable MUST be unique among the names of all variables defined
within the same immediately enclosing scope.

@item 24 @tab static analysis @tab
Variable names are @code{BPELVariableNames}, that is, NCNames (as defined in
@acronym{XML} Schema specification) but in addition they MUST NOT contain the
@samp{.} character.

@item 25 @tab static analysis @tab
The @code{messageType}, type or @code{element} attributes are used to specify
the type of a variable. Exactly one of these attributes MUST be used.

@item 44 @tab static analysis @tab
The name of a @code{<correlationSet>} MUST be unique among the names of all
@code{<correlationSet>} defined within the same immediately enclosing scope.

@item 51 @tab static analysis @tab
The @code{inputVariable} attribute MUST NOT be used on an @code{Invoke}
activity that contains @code{<toPart>} elements.

@item 52 @tab static analysis @tab
The @code{outputVariable} attribute MUST NOT be used on an @code{Invoke}
activity that contains @code{<toPart>} elements.

@item 55 @tab static analysis @tab
For @code{<receive>}, if @code{<fromPart>} elements are used on a
@code{<receive>} activity then the variable attribute MUST NOT be used on the
same activity.

@item 56 @tab static analysis @tab
A ``start activity'' is a @code{<receive>} or @code{<pick>} activity that is
annotated with a @code{createInstance="yes"} attribute. Activities other than
the following: start activities, @code{<scope>}, @code{<flow>} and
@code{<sequence>} MUST NOT be performed prior to or simultaneously with start
activities.

@item 57 @tab static analysis @tab
If a process has multiple start activities with correlation sets then all such
activities MUST share at least one common correlationSet and all common
correlationSets defined on all the activities MUST have the value of the
@code{initiate} attribute be set to @code{"join"}.

@item 59 @tab static analysis @tab
For @code{<reply>}, if @code{<toPart>} elements are used on a @code{<reply>}
activity then the @code{variable} attribute MUST NOT be used on the same
activity.

@item 62 @tab static analysis @tab
If @code{<pick>} has a @code{createInstance} attribute with a value of
@samp{yes}, the events in the @code{<pick>} MUST all be @code{<onMessage>}
events.

@item 63 @tab static analysis @tab
The semantics of the @code{<onMessage>} event are identical to a
@code{<receive>} activity regarding the optional nature of the @code{variable}
attribute or @code{<fromPart>} elements, if @code{<fromPart>} elements on an
activity then the variable attribute MUST NOT be used on the same activity
(see SA00055).

@item 64 @tab static analysis @tab
For @code{<flow>}, a declared link's name MUST be unique among all
@code{<link>} names defined within the same immediately enclosing
@code{<flow>}.

@item 65 @tab static analysis @tab
The value of the @code{linkName} attribute of @code{<source>} or
@code{<target>} MUST be the name of a @code{<link>} declared in an enclosing
@code{<flow>} activity.

@item 66 @tab static analysis @tab
Every link declared within a @code{<flow>} activity MUST have exactly one
activity within the @code{<flow>} as its source and exactly one activity within
the @code{<flow>} as its target.

@item 67 @tab static analysis @tab
Two different links MUST NOT share the same source and target activities; that
is, at most one link may be used to connect two activities.

@item 68 @tab static analysis @tab
An activity MAY declare itself to be the source of one or more links by
including one or more @code{<source>} elements. Each @code{<source>}
element MUST use a distinct link name.

@item 69 @tab static analysis @tab
An activity MAY declare itself to be the target of one or more links by
including one or more @code{<target>} elements. Each @code{<target>} element
associated with a given activity MUST use a link name distinct from all other
@code{<target>} elements at that activity.

@item 70 @tab static analysis @tab
A link MUST NOT cross the boundary of a repeatable construct or the
@code{<compensationHandler>} element. This means, a link used within a
repeatable construct (@code{<while>}, @code{<repeatUntil>}, @code{<forEach>},
@code{<eventHandlers>}) or a @code{<compensationHandler>} MUST be declared in
a @code{<flow>} that is itself nested inside the repeatable construct or
@code{<compensationHandler>}.

@item 71 @tab static analysis @tab
A link that crosses a @code{<catch>}, @code{<catchAll>} or
@code{<terminationHandler>} element boundary MUST be outbound only, that is,
it MUST have its source activity within the @code{<faultHandlers>} or
@code{<terminationHandler>}, and its target activity outside of the scope
associated with the handler.

@item 72 @tab static analysis @tab
A @code{<link>} declared in a @code{<flow>} MUST NOT create a control cycle,
that is, the source activity must not have the target activity as a logically
preceding activity.@footnote{This fault can only be detected in mode mode @samp{cfg}.}

@item 73 @tab static analysis @tab
The expression for a join condition MUST be constructed using only Boolean
operators and the activity's incoming links' status values.

@item 74 @tab static analysis @tab
The expressions in @code{<startCounterValue>} and @code{<finalCounterValue>}
MUST return a TII (meaning they contain at least one character) that can be
validated as a @code{xsd:unsignedInt}. Static analysis MAY be used to detect
this erroneous situation at design time when possible (for example, when the
expression is a constant).

@item 75 @tab static analysis @tab
For the @code{<forEach>} activity, @code{<branches>} is an integer value
expression. Static analysis MAY be used to detect if the integer value is
larger than the number of directly enclosed activities of @code{<forEach>} at
design time when possible (for example, when the branches expression is a
constant).

@item 76 @tab static analysis @tab
For @code{<forEach>} the enclosed scope MUST NOT declare a variable with the
same name as specified in the @code{counterName} attribute of
@code{<forEach>}.

@item 77 @tab static analysis @tab
The value of the @code{target} attribute on a @code{<compensateScope>}
activity MUST refer to the name of an immediately enclosed @code{scope} of the
@code{scope} containing the FCT-handler with the @code{<compensateScope>}
activity. This includes immediately enclosed scopes of an event handler
(@code{<onEvent>} or @code{<onAlarm>}) associated with the same @code{scope}.

@item 78 @tab static analysis @tab
The @code{target} attribute of a @code{<compensateScope>} activity MUST refer
to a @code{scope} or an @code{invoke} activity with a fault handler or
compensation handler.

@item 79 @tab static analysis @tab
The root @code{scope} inside a FCT-handler MUST not have a compensation
handler.

@item 80 @tab static analysis @tab
There MUST be at least one @code{<catch>} or @code{<catchAll>} element within
a @code{<faultHandlers>} element.

@item 81 @tab static analysis @tab
For the @code{<catch>} construct; to have a defined type associated with the
fault variable, the @code{faultVariable} attribute MUST only be used if either
the @code{faultMessageType} or @code{faultElement} attributes, but not both,
accompany it. The @code{faultMessageType} and @code{faultElement} attributes
MUST NOT be used unless accompanied by @code{faultVariable} attribute.

@item 82 @tab static analysis @tab
The peer-scope dependency relation MUST NOT include cycles. In other words,
@acronym{WS-BPEL} forbids a process in which there are peer scopes S1 and S2
such that S1 has a peer-scope dependency on S2 and S2 has a peer-scope
dependency on S1.@footnote{This fault can only be detected in mode mode @samp{cfg}.}

@item 83 @tab static analysis @tab
An event handler MUST contain at least one @code{<onEvent>} or
@code{<onAlarm>} element.

@item 84 @tab static analysis @tab
The @code{partnerLink} reference of @code{<onEvent>} MUST resolve to a partner
link declared in the process in the following order: the associated scope
first and then the ancestor scopes.

@item 88 @tab static analysis @tab
For @code{<onEvent>}, the resolution order of the @code{correlation set}(s)
referenced by @code{<correlation>} MUST be first the associated scope and then
the ancestor scopes.

@item 91 @tab static analysis @tab
A scope with the @code{isolated} attribute set to @code{"yes"} is called an
isolated scope. Isolated scopes MUST NOT contain other isolated scopes.

@item 92 @tab static analysis @tab
Within a scope, the name of all named immediately enclosed scopes MUST be
unique.

@item 93 @tab static analysis @tab
Identical @code{<catch>} constructs MUST NOT exist within a
@code{<faultHandlers>} element.

@item 100 @tab notice @tab
Either a non-standard element@footnote{All elements
that are not explicitly defined in the @acronym{WS-BPEL} specification (e.g.@:,
elements from other namespaces) are considered as ``non-standard''.} was parsed
or a @acronym{BPEL} activity was considered as
misplaced. In the first case, a non-standard element was parsed when the
parser expected a @acronym{BPEL} standard activity. Then, a syntax error is
printed and the whole element is ignored. The parse error and this message
can usually be ignored, as non-standard elements would neither we translated
to a Petri net model nor are constrained by the @acronym{WS-BPEL}
specification.

In the second case, a syntactically correct @acronym{BPEL}
was skipped, because it was misplaced. As an example, consider two activities
embedded in a @code{<while>} activity without an enclosing @code{<sequence>}
activity. In this case, the second activity triggers this message.

@item 101 @tab notice @tab
The @code{<partners>} construct (only supported by @acronym{BPEL4WS} 1.1) is skipped due
to a syntax error.

@item 102 @tab notice @tab
The @code{<to>} or @code{<from>} construct is skipped due to a syntax error.

@item 103 @tab notice @tab
The @code{<condition>} construct is skipped due to a syntax error.

@item 104 @tab critical @tab
When a syntax error occurs, BPEL2oWFN tries to recover and continues parsing the
input file after skipping the faulty or unknown element. Sometimes, however,
the skipping of activities yields to situations where a further analysis of the
@acronym{BPEL} process is impossible. In this case, the syntax of the process
has to be fixed or non-standard elements have to be removed or out-commented.

@item 105 @tab notice @tab
When a syntax error occurs, BPEL2oWFN tries to recover and continues parsing the
input file after skipping the faulty or unknown element. If it is possible to
continue, the analysis results might be faulty. In this case, the syntax of the
process has to be fixed or non-standard elements have to be removed or
out-commented.

@item 106 @tab warning @tab
@acronym{CFG} analysis detected two receiving activities (i.e., @code{<receive>},
@code{<onEvent>}, @code{<onMessage>}, synchronous @code{<invoke>}) that might
be activated concurrently and share the same partner link, port type, operation,
and correlation set. When a message is sent to the process, these activities
are in @i{conflict}; that is, it is not defined which activity will receive an
inbound message. At runtime, the standard fault @samp{bpel:conflictingReceive}
would be thrown.@footnote{This fault can only be detected in mode mode @samp{cfg}.}

@item 107 @tab warning @tab
A mandatory attribute of an activity was not defined. Especially for
communicating activities, the absence of @code{partnerLink} and
@code{operation} might hamper the subsequent analysis and Petri net generation.

@item 108 @tab syntax @tab
An attribute was set to a value that violates the attribute's given type. Only
the types @code{tBoolean}, @code{tInitiate}, @code{tRoles}, and
@code{tPattern} are checked.

@item 109 @tab warning @tab
A variable referenced in an activity was not defined before; that is, no
matching @code{<variable>} definition was found in a parent scope.

@item 110 @tab warning @tab
A partner link referenced in an activity was not defined before; that is, no
matching @code{<partnerLink>} definition was found in the process.

@item 111 @tab warning @tab
A correlation set referenced in an activity was not defined before; that is, no
matching @code{<correlationSet>} definition was found in a parent scope.

@item 112 @tab notice @tab
The @code{<literal>} construct is skipped due to a syntax error.

@item 113 @tab syntax @tab
A @acronym{UTF}-8 character was read in the input file. As BPEL2oWFN's scanner does not
support Unicode, all @acronym{UTF}-8 characters are ignored. This message is only
displayed when the first @acronym{UTF}-8 character is read.

@item 114 @tab warning @tab
@acronym{CFG} analysis detected a read access to a variable that was not
initialized before. At runtime, the standard fault
@samp{bpel:uninitializedVariable} would be thrown.@footnote{This fault can only be detected in mode mode @samp{cfg}.}

@item 115 @tab notice @tab
The process definition defines an abstract process profile, and thus allows
several ``opaque'' constructs. When processing and analyzing an abstract
process, BPEL2oWFN might report error messages that where designed for
executable processes, for example missing attributes. Static analysis errors
detected in an abstract process are reported as warnings.

@item 116 @tab notice @tab
An @code{<opaqueActivity>} of an abstract process was replaced by an
@code{<empty>} activity.

@item 117 @tab notice @tab
When using the parameter @samp{communicationonly}, the occurrence of join
failures is not modeled. Thus, any activity is treated as if the
attribute @samp{suppressJoinFailure} is set to @samp{yes}.@footnote{If the
attribute @samp{suppressJoinFailure} is not explicitly defined for an
activity, the value is inherited by the parent activity.}

@item 118 @tab notice @tab
A user-defined transition condition is ignored and modeled as ``@i{n}-out-of-@i{n}''
(@samp{true}) instead.

@item 119 @tab notice @tab
A user-defined transition condition is ignored and modeled as ``1-out-of-@i{n}''
(XOR) instead.

@item 120 @tab notice @tab
When using the parameter @samp{communicationonly}, the FTC (fault, termination,
and compensation) handlers are not modeled.

@item 121 @tab notice @tab
When using the parameter @samp{communicationonly}, activities of the negative
control flow (@code{<exit>}, @code{<throw>}, @code{<compensate>}, and
@code{<compensateScope>}) are replaced by an @code{<empty>} activity.

@end multitable



@c @section Exit Values

@c When BPEL2oWFN is invoked and run without any error, the
@c exit value is 0.


@c Please report the occurrence of any exception with numbers 30--50
@c since it indicates a bug in BPEL2oWFN we would like to fix
@c immediately (see @ref{Reporting Bugs}).





@c ----------------------------------------------------------------------------

@node File Formats
@chapter File Formats

In this chapter, we show how a @acronym{BPEL} process can be translated to a Petri net model an then exported to several output file formats. Consider the following simple @acronym{BPEL} process @file{example.bpel}:

@smallexample

<process name="exampleprocess" targetNamespace="www.gnu.org/software/bpel2owfn">
  <partnerLinks>
    <partnerLink name="PL" partnerLinkType="PLT"
      myrole="exampleprocess" partnerRole="exampleuser" />
  </partnerLinks>

  <sequence>
    <receive partnerLink="PL" operation="req" createInstance="yes" />
    <reply partnerLink="PL" operation="ack" />
  </sequence>
</process>

@end smallexample

This process just waits for a message @samp{req} on partner link @samp{PL} and replies to this message with @samp{ack} on the same partner link. To parse this @acronym{BPEL} process, BPEL2oWFN has to be invoked with

@cartouche
@smallexample
bpel2owfn -i example.bpel
@end smallexample
@end cartouche

which responds with the output:

@smallexample

==============================================================================
GNU BPEL2oWFN 2.0.0 reading from file `example.bpel'
------------------------------------------------------------------------------
------------------------------------------------------------------------------
3 activities (2 basic, 1 structured, 0 scopes) + 3 implicit activities
0 handlers (0 FH, 0 TH, 0 CH, 0 EH) + 1 implicit handlers
0 links, 0 variables

[SYNTAX ANALYSIS] No syntax errors found.
[STATIC ANALYSIS] No errors found checking 44 statics analysis requirements.
[OTHER ANALYSIS]  No other errors found.
------------------------------------------------------------------------------

@end smallexample

This means, the process consists of three activities (two basic activities and
one structured activities), no handlers, no links and no variables. On the
bottom the analysis results are summarized: no syntactic, static, or other
error was found.

Furthermore, three ``implicit'' activities are counted: The @acronym{WS-BPEL}
specification describes several implicit transformations of the input process,
as well as standard fault, termination and compensation handlers. In the
considered @acronym{BPEL} process, no fault handlers are specified. Thus, a
standard fault handler is added by BPEL2oWFN:

@smallexample
<faultHandlers>
  <catchAll>
    <sequence>
      <compensate />
      <rethrow />
    </sequence>
  </catchAll>
</faultHandlers>
@end smallexample

To see how the @acronym{BPEL} process looks like after applying the transformation rules and adding the standard handlers, BPEL2oWFN output the manipulated process using its pretty-printer:

@cartouche
@smallexample
bpel2owfn -i example.bpel -m pretty
@end smallexample
@end cartouche

The manipulated process looks like this:

@smallexample

<process id="1" abstractProcess="no" exitOnStandardFault="no" name="exampleprocess"
 suppressJoinFailure="no" targetNamespace="www.gnu.org/software/bpel2owfn">
  <partnerLinks>
    <partnerLink id="3" myrole="exampleprocess"
       name="PL" partnerLinkType="PLT" partnerRole="exampleuser" />
  </partnerLinks>
  <faultHandlers id="4">
    <catchAll id="13">
      <sequence id="12" suppressJoinFailure="no">
        <compensate id="11" suppressJoinFailure="no">
        </compensate>
        <rethrow id="10">
        </rethrow>
      </sequence>
    </catchAll>
  </faultHandlers>
  <sequence id="7" suppressJoinFailure="no">
    <receive id="8" createInstance="yes" operation="req"
       partnerLink="PL" suppressJoinFailure="no">
    </receive>
    <reply id="9" operation="ack" partnerLink="PL" suppressJoinFailure="no">
    </reply>
  </sequence>
</process>

@end smallexample

Each activity is printed together with its attributes. Note that the standard values of several attributes (e.g., @samp{abstractProcess} or @samp{suppressJoinFailure}) are added. Furthermore, an identifier (attribute @samp{id}) was added to every activity.

We now want to create a compact Petri net model of the @acronym{BPEL} process, using the @samp{petrinet} mode and the @samp{communicationonly} parameter:

@cartouche
@smallexample
bpel2owfn -i example.bpel -m petrinet -p communicationonly
@end smallexample
@end cartouche

BPEL2oWFN now also displays statistics of the generated Petri net model:

@smallexample
|P|=5, |P_in|= 1, |P_out|= 1, |T|=2, |F|=6
@end smallexample

The generated Petri net model consists of five places, including one input and one output place, two transitions and six arcs. To create a graphical representation, invoke BPEL2oWFN with the following options:

@cartouche
@smallexample
bpel2owfn -i example.bpel -m petrinet -p communicationonly -f dot -o
@end smallexample
@end cartouche

This command creates a file @file{example.dot}, containing a Graphviz dot representation of the Petri net, and---if the @code{dot} tool was found in the search path---a @acronym{PNG, Portable Network Graphics} an image file @file{example.png}. The latter looks like this:@*

@iftex
@center @image{images/example,,2.5in}
@end iftex
@ifhtml
@center @image{images/example}
@end ifhtml

The graphic depicts the generated open workflow net. The inner of the net, that is, all nodes
except the interface places, are depicted inside the dashed box, whereas the interface is depicted
outside the frame. Input places and all connected transitions are colored orange. Similarly, output
places and connected transitions are colored yellow. Gray places belong to the final marking, that
is, the marking [@b{p3}] is the final marking of the @acronym{oWFN}.

To reach this final marking, the environment has to send a message @b{in.PL.req}, followed by
receiving a message @b{out.PL.ack}. The name of the communication places is composed by the
communication direction (``in'' or ``out''), the partner link's name (@samp{PL}) and the operations
name (@samp{req} or @samp{ack}).

For this very small process, it is easy to validate the generated Petri net model, that is, to
compare the intended semantics by the actually modeled semantics. Especially the correlation
between the nodes of the Petri net and the activities of the input @acronym{BPEL} process is not
obvious for larger processes. To this end,

@cartouche
@smallexample
bpel2owfn -i example.bpel -m petrinet -p communicationonly -f info
@end smallexample
@end cartouche

displays an information file, consisting of all the Petri net nodes' roles.

@smallexample

PLACES:
ID      TYPE            ROLES
p1      internal        1.internal.initial
                        7.initial
                        7.internal.initial
                        8.initial
                        8.internal.initial
p2      internal        8.final
                        8.internal.final
                        9.initial
                        9.internal.initial
p3      internal        1.internal.final
                        7.final
                        7.internal.final
                        9.final
                        9.internal.final
in.PL.req       input           in.PL.req
out.PL.ack      output          out.PL.ack

TRANSITIONS:
ID      ROLES
t1      8.internal.receive
t2      9.internal.reply

@end smallexample

This file has to be read as follows: the place @samp{p1} has the type internal (i.e., is not
connected with an interface place) and has the roles @samp{1.internal.initial}, @samp{7.initial},
@samp{7.internal.initial}, @samp{8.initial}, and @samp{8.internal.initial}. While the prefix of
each role is the identifier of an activity (@samp{1} for the @code{<process>}, @samp{7} for the
@code{<sequence>}, and @samp{8} for the @code{<receive>}), the suffix specifies the role inside the
respective pattern. Without going too much into details, @samp{1.internal.initial} is the role of
the initial place of the pattern for the @code{<process>}, whereas, for example
@samp{7.internal.final} is the final place of the @code{<sequence>}'s pattern. Similarly, roles of
transitions are specified. Multiple roles of a single place arise due to the merging of distinct
places during the composition of the several patterns.

Now that we have convinced ourselves that the generated net reflects the intended behavior of the
@acronym{BPEL} process, we can export the Petri net model to an output file to process it by
analysis tools. In this case, we want to create a Fiona open workflow net executing

@cartouche
@smallexample
bpel2owfn -i example.bpel -m petrinet -p communicationonly -f ownf -o
@end smallexample
@end cartouche

which creates a file @file{example.owfn}:

@smallexample

@{
  generated by: BPEL2oWFN 2.0.0
  input file:   `example.bpel' (process `exampleprocess')
  invocation:   `bpel2owfn -i example.bpel -m petrinet -p communicationonly -f owfn'
  net size:     |P|=5, |P_in|= 1, |P_out|= 1, |T|=2, |F|=6
@}

PLACE
  INTERNAL
    p1, p2, p3;

  INPUT
    in.PL.req @{$ MAX_OCCURRENCES = 1 $@};

  OUTPUT
    out.PL.ack @{$ MAX_OCCURRENCES = 1 $@};


INITIALMARKING
  p1:    1 @{initial place@};

FINALMARKING
  p3 @{final place@};


TRANSITION t1 @{ input @}
  CONSUME in.PL.req, p1;
  PRODUCE p2;

TRANSITION t2 @{ output @}
  CONSUME p2;
  PRODUCE out.PL.ack, p3;


@{ END OF FILE `example.owfn' @}

@end smallexample


This is finally the @acronym{oWFN} model of the @acronym{BPEL} process that can be analyzed by
Fiona@footnote{Fiona is available at @url{http://www.informatik.hu-berlin.de/top/tools4bpel}.}.






@c ----------------------------------------------------------------------------

@ignore

@node Petri Net Patterns
@chapter Petri Net Patterns
In version @value{VERSION} of BPEL2oWFN the following Petri net
patterns are implemented:



@section Petri net semantics from [Sta05]

The Petri net semantics for @acronym{BPEL4WS} from Christian Stahl
(Humboldt-Universit@"at zu Berlin) published in [Sta05].

@subsection Overview

Feature complete semantics covering both positive control flow with
event handling and negative control flow (fault and compensation
handling).

@anchor{Limitations of the semantics}
@subsection Limitations of the semantics
@itemize

@item Only one instance of a @acronym{BPEL} process can be
transformed into a Petri net.

@item The semantics abstracts from the connection of a
@acronym{BPEL} process to its partner processes. The interface of a
@acronym{BPEL} process is transformed into a set of message
channels, i.e.@: places in the Petri net.

@item In our Petri net patterns we model data, but we abstract from
the definition of the functions which edit the data. Furthermore, we
did not specify the transition guards and so we did not specify
which circumstances are necessary that a specific fault can occur.

@item Every activity is limited to one correlation set (except the
synchronous invoke which is limited to two correlation sets).

@end itemize


@anchor{Changes and Modulation}
@subsection Changes and Modulation

We tried to stick as close to the Petri net patterns of [Sta05] as
possible. However, the implemented patterns in the pattern database
sometimes differ to the given patterns due to discovery of bugs or
implementation decisions. In this subsection we sum up these changes
to help you understand the generated Petri net model.

@itemize

@item @b{Fault model}. At most one error can occur in the positive
control flow of each scope or process. Yet this confines the
possible runs of the process it is only a little change of the
semantics, since --- according to the specification --- only the
first fault is handled anyway. While further faults occurring before
the positive control flow is stopped are ignored in the original
semantics of [Sta05] (in fact, the faults are collected on place
@samp{fault_in} and then consumed by a reset arc) they are prevented
in the implemented semantics. In our model, exactly the @i{first}
occurring fault is handled, whereas in [Sta05] one fault is chosen
non-deterministically.

Furthermore, all @samp{failed} places of the activities were
removed. In the original Petri net semantics, all faults of a scope
were collected on the @samp{fault_in} of the stop-pattern and then
classified as being the first fault of the scope, a following fault,
a fault from the fault handler, a fault from the compensation
handler, or a fault from a child scope. In our implementation, new
places (@samp{fh_fault_in} and @samp{ch_fault_in}) were introduced
and each activity throws its faults to the ``correct'' place
automatically.

To ensure that at most one error can occur (i.e.@: at most one token
is produced on any fault place) the fault places are guarded by
state places: To throw a fault from an activity enclosed in a scope,
the state of that scope has to be @samp{Active}. The first thrown
fault changes the state to @samp{!Active} thus preventing more
faults to occur. The places @samp{fh_fault_in} and
@samp{ch_fault_in}, resp.@: are guarded by
@samp{!FHFaulted}/@samp{FHFaulted} and
@samp{!CHFaulted}/@samp{CHFaulted}, resp.

Moreover, the generated Petri nets have less nodes than those
generated by @acronym{BPEL2PN} [SHS05] since an unfolding of the
reset arcs in not necessary any more.

@item @b{Standard faults}. The ``throw-fault'' and ``stop'' transitions
are generated using parameterized functions. With the command-line parameter
@samp{--parameter=nostandardfaults} all @acronym{BPEL} standard faults
that can occur in the activities (i.e. all faults except user-defined faults
in a throw activity or join failures) are suppressed. The generated models
have a smaller state space and allow the analysis for controllability
which is impossible without the assumption that messages can always be
sent faultlessly.

In order not to suppress standard faults at all, the command-line parameter
@samp{--parameter=nofhfaults} can be used to allow standard faults outside
fault handlers, i.e.@: to create models that allow the occurrence of one
standard fault in each scope yet disallow to occurrence of further faults.

@item @b{1-safety}. The new modeling of the fault management yields
to 1-safe Petri nets (i.e.@: any reachable state of the Petri net
model puts at most one token on each place of the net).

Beside performance (e.g.@: only 1 bit is needed to store the marking
of a place) and compatibility issues (e.g.@: 1-safety is a
prerequisite to use the Model-Checking Kit [MCK]), features not
supported by the Petri net semantics can be discovered since the
generated net will most likely violate 1-safety when an unsupported
@acronym{BPEL} feature is used. If, for example, a scope is enclosed
in a while loop (which would model instantiation which is not
supported by the Petri net semantics @ref{Limitations of the
semantics}), the state places of that scope would not be 1-safe.

@item @b{Assign activity}. All copy branches of an assign activity
are modeled in a single pattern (i.e.@: Fig.@: 6 and Fig.@: 7 are merged).
Furthermore, when an error (outside that activity) occurs, an active
assign-activity is not stopped until all copy branches have
finished. This is described in [ACD@math{^+}03] as:

@quotation
The assign activities are sufficiently short-lived that they are allowed to
complete rather than being interrupted when termination is forced.
@end quotation

This change fixes a bug in the Petri net semantics.

@item @b{While activity}. Since the original semantics does not support
instances of the BPEL process, while activities were poorly supported and
usually produced non 1-safe Petri nets or deadlocks as links embedded in
the while activity were evaluated incorrectly. In the implementation the
while activity is acyclic: the embedded activity is now executed at most
once (whether or not it is executed is decided non-deterministically).

The ``original'' behavior can be restored with the command-line parameter
@samp{--parameter=cyclicwhile}.

@item @b{Event handlers}. There is one pattern for both alarm and
message event handlers (i.e.@: Fig.@: 29 and Fig.@: 30 are merged). When
no event handler is specified, an ``implicit'' event handler is
installed which is just a stub and does not change the semantics. The
message event handlers are acyclic by default to create acyclic Petri net
models. However, the ``original'' behavior can be restored with the
command-line parameter @samp{--parameter=cycliceh}.

@item @b{Deadlocks}. A transition named @samp{1.internal.finalloop}
can be added to livelock the process upon completion using the command-line
parameter @samp{--parameter=finalloop}. This leads to
deadlock-free Petri nets in case of processes with ``reasonable''
control flow and helps to find unwanted deadlocks occurring due
wrong modeling. If, for example, the links of a process model are
cyclic the generated Petri net will deadlock.

In future versions of BPEL2oWFN these found deadlocks
shall be mapped back into the @acronym{BPEL} code to highlight the
``unreasonable'' activities (i.e.@: a cycle-closing link).

@item @b{Unfoldings of high-level places}. Due to the abstraction (high-level to
low-level) of the patterns some places were unfolded: the place
@samp{compScope} of Fig.@: 42--44 usually holding a token with a name
of a scope is unfolded to @samp{compScope.@var{scopename}} and only
merged with the @samp{ch_in}-place of that respective scope. In all
other cases the places are ``converted'' to low-level places so the
generated model completely abstracts from data.

@item @b{Link semantics}. The generated Petri net model always
generates @samp{negLink} places for structured activities
independently of the presence of links. Anyway, the semantics is not
changed since the resulting subnets are dead in this case.

@item @b{Correlation sets}. Correlation sets are not implemented and
are simply ignored during parsing.
@end itemize





@c ----------------------------------------------------------------------------

@node Petri Net-related Functions
@chapter Petri Net-related Functions

Currently implemented Petri net-specific functions:
@section Structural Simplification

BPEL2oWFN implements the following structural reduction rules:

@c @float
@c @center @noindent @image{images/ra1,,1.2in}@ @ @ @ @ @ @ @ @ @ @image{images/rb1,,1.2in}
@c @sp 1
@c @center @noindent @image{images/ra2,,1.2in}@ @ @ @ @ @ @ @ @ @ @image{images/rb2,,1.2in}
@c @sp 1
@c @end float


@itemize
@item If two transitions @math{t_1} and @math{t_2} have the same
preset and postset, one of them can be removed.

@item If a transition has a singleton preset and postset, the
transition can be removed (sequence) and the preset and postset can
be merged.

@item All places with empty preset and postset (isolated places) are
removed.
@end itemize

These structural reduction rules are implemented in the command-line option
@samp{--parameter=simplify}, see @ref{Invoking BPEL2oWFN}). To achieve a
better reduction, combine the parameter with @samp{--parameter=novarialbles}.



@section Abstractions
@itemize

@item To obtain a place/transition Petri net from an open workflow
net the communication places are removed. This abstraction from
communicational behavior is used in all Petri net output formats
except @acronym{oWFN} (@samp{--format=owfn}).

@item The original Petri net semantics [Sta05] consists of high-level
Petri net patterns. However, the models generated from BPEL2oWFN
abstract from data. Therefore all transition guards, arc inscriptions
and arc types were ``converted'' to low-level constructs: all
transition guards and arc inscriptions were removed (decisions are
now made non-deterministically) and read arcs are ``unfolded'' to
loops. Due to a new fault management (see @ref{Changes and
Modulation}) the patterns do not contain any reset arcs and is 1-safe.
@end itemize



@section Markings

The following places are initially marked to ensure a deadlock-free
model of processes with ``reasonable'' control-flow (e.g.@: with an
acyclic link structure):

@itemize
@item the initial place of the process (@samp{1.internal.initial}),

@item the variable places (@samp{variable.@var{variablename}}), and

@item the clock (@samp{1.internal.clock}) if the process embeds an
alarm event handler or a @code{<wait>} activity.
@end itemize

@end ignore


@c ----------------------------------------------------------------------------

@node FAQ and Known Bugs
@chapter FAQ and Known Bugs


@section Frequently Asked Questions

@itemize
@item @b{Why does the parser reject my @acronym{BPEL} file?}

BPEL2oWFN uses Flex and Bison to implement the parser. We decided do not use an
off-the-shelf @acronym{XML} parser generator as we did not found a suitable
platform-independent parser generator whose license was ``compatible'' to the
GNU @acronym{GPL, General Public License}. Furthermore, we use the
term generator Kimwitu++ to describe and process the
@acronym{AST, abstract syntax tree}, and the trio Flex/Bison/Kimwitu++
integrates seamlessly. Though the grammar has to be defined manually, the
generated parser is very flexible as it allows to process @acronym{BPEL4WS} 1.1,
@acronym{WS-BPEL} 2.0, and to some extend @acronym{BPEL4WS} 1.0 processes.

However, the parser does not support @acronym{XML} namspaces. To
this end, @acronym{BPEL} constructs are only recognized if the are either
unprefixed or using the prefix @samp{bpws:}. Any other elements are skipped
by the parser of BPEL2oWFN. Nevertheless, processes that use such elements might be
rejected with a syntax error message (cf.@: warning message [W00104]).

As a solution, try removing or commenting non-standard elements, and remove any
namespace prefixed from @acronym{BPEL} elements.


@item @b{I validated my process using an @acronym{XML} validator. Why does
BPEL2oWFN still reports syntax errors?}

Well, because there @i{are} such errors. Many @acronym{BPEL} editors generate
invalid @acronym{BPEL}. Even the @acronym{WS-BPEL} specification contained
processes with syntax errors for a long time. Furthermore, a lot of syntax errors
cannot be covered with @acronym{XSD, XML Schema Definition} validation. Even if
the considered process run on existing engines, BPEL2oWFN might reject it, as
it stubbornly follows the @acronym{WS-BPEL} specification.


@item @b{Why @acronym{LoLA} does not accept the generated files and reports parse
errors in the first line?}

This problem occurs using a pre-compiled windows version of BPEL2oWFN.
The generated files are in Windows format, yet @acronym{LoLA} only supports
files in Unix format. To overcome this limitation of @acronym{LoLA}, use a
tool like @samp{dos2unix} or change the file format in an editor like @samp{vi}.

@end itemize


@section Known Bugs

Though this is the second major release version of BPEL2oWFN, it might
still contain poorly tested, inefficient code.


@itemize

@item @b{Problem:} BPEL2oWFN crashes during the translation of an abstract
@acronym{BPEL} process.

@b{Diagnosis:} The implemented semantics of was mainly created to support
executable @acronym{BPEL} processes. Therefore, the translation of abstract
@acronym{BPEL} processes (formerly called @i{business protocols}) might be
buggy. In particular, the allowed absence of implementation details hampers
the analysis of the process and the generation of a formal model.

@b{Solution:} To avoid errors, at least each communicating activity should be
defined with @code{partnerLink} and @code{operation} attribute, and
@code{<invoke>} activities should be defined with @code{inputVariable} and/or
@code{outputVariable} to distinguish the respective asynchronous and synchronous
occurrence.
@end itemize



@anchor{Reporting Bugs}
@section Reporting Bugs

If you find a bug in BPEL2oWFN or have a question, please first check that
it is not a known bug or a frequently asked question listed in above. Otherwise,
please send us an email to @email{bug-bpel2owfn@@gnu.org}. Include the version
number which you can find by running @samp{bpel2owfn --version}. Also include in
your message the input @acronym{BPEL} process and the output that the program
produced. We will try to answer your mail within a week.

If you have other questions, comments or suggestions about BPEL2oWFN,
contact us via electronic mail to @email{nlohmann@@informatik.hu-berlin.de}.



@section Contact Person
Niels Lohmann

Humboldt-Universit@"at zu Berlin@*
Institut f@"ur Informatik@*
Unter den Linden 6@*
10099 Berlin, Germany

@table @asis
@itemx Homepage
@url{http://www.informatik.hu-berlin.de/top/mitarbeiter/lohmann}

@itemx E-mail
@email{nlohmann@@informatik.hu-berlin.de}

@itemx Skype
nlohmann

@itemx Phone
(+49) (30) 2093-3070

@itemx Fax
(+49) (30) 2093-3067
@end table




@section Help BPEL2oWFN
BPEL2oWFN is now developed for one and a half year, and grown to a quite big
program. Since November 2006, BPEL2oWFN is a GNU package, and the development
is organized at Savannah (@url{https://savannah.gnu.org/projects/bpel2owfn}).
We are always looking for developers and testers that can help us improving
BPEL2oWFN.




@c ----------------------------------------------------------------------------

@ignore

@node Future Work
@chapter Future Work

For future releases of BPEL2oWFN the following features are planned:

@itemize

@c @item @b{Flexible model generation}. Originally, BPEL2oWFN
@c was designed to support flexible model generation, i.e.@: finding the
@c most abstract (thus smallest) model capable to check a given
@c property. With static analysis we hope to generate the smallest
@c Petri net possible to check properties like deadlock-freedom or
@c controllability.

@item @b{Add data aspects}. In the implemented patterns we abstract
from data and do not evaluate join or transition conditions. Instead all
decisions are made non-deterministically. With static analysis it is
possible to find the relevant ranges of values that allow a replacement
of non-deterministic choices with choices made evaulating data. This
technique (called @i{abstract interpretation}) might help to reduce the
modelled behavior of the process yet being more precise.

@item @b{Control flow analysis}. In [Hei03] a control flow graph for
@acronym{BPEL} was introduced. This control flow graph (currently
implemented prototypic) is the base for more sophisticated analysis,
e.g.@: finding unreachable activities, uninitialized variables or
other problems that can occur during runtime.

@c @item @b{More Petri net patterns}. Being feature-complete the Petri
@c nets generated from the Petri net semantics of [Sta05] consist of a
@c large number of nodes and might be to large to be analyzed by model
@c checkers. The elaboration of different petri net patterns
@c specialized for certain purposes (e.g.@: omitting the negative control
@c flow) does not only help to find smaller models, but is also a
@c prerequisite for flexible model generation.

@item @b{Detailed info-files}. The generated info-files currently just
list the nodes of the generated net. To help the retranslation of Petri
net-specific properties to the input process the generated files have
to be more detailed. The integration of a symbol table is currently
in pre-beta state and should be finished in the next version of
BPEL2oWFN.

@item @b{Support for @acronym{WS-BPEL}}. The specification of
@acronym{WS-BPEL, Web Service Business Process Execution Language}
version 2.0 is in its final phase. As soon as the standardization is
completed, @acronym{WS-BPEL} can be supported by BPEL2oWFN
by overworking the grammar and adding appropriate patterns to the
pattern database.

@end itemize





@c ----------------------------------------------------------------------------

@node References
@appendix References

@table @asis

@item [ACD@math{^+}03]
Tony Andrews, Francisco Curbera, Hitesh Dholakia, Yaron Goland, Johannes Klein,
Frank Leymann, Kevin Liu, Dieter Roller, Doug Smith, Satish Thatte, Ivana
Trickovic, and Sanjiva Weerawarana. @b{Business Process Execution Language for
Web Services, Version 1.1}. Technical report, BEA Systems, IBM, Microsoft, SAP,
Siebel Systems. May 2003.

@item [BKK95]
Falko Bause, Peter Kemper, and Pieter Kritzinger. @b{Abstract Petri Net
Notation}. @i{Petri Net Newsletter} 49:9-27, October 1995.
@footnote{@url{http://ls4-www.informatik.uni-dortmund.de/QM/MA/fb/publication_ps_files/APNN.ps.gz}}

@item [Fiona]
Peter Massuthe and Daniela Weinberg. @b{Fiona}.@footnote{@url{http://www.informatik.hu-berlin.de/top/tools4bpel/fiona}}

@item [Hei03]
Thomas Heidinger. @b{Statische Analyse von BPEL4WS-Prozessmodellen} @i{(in German)}.
Studienarbeit, Humboldt-Universit@"at zu Berlin, December 2003.
@footnote{@url{http://www.informatik.hu-berlin.de/top/download/publications/heidinger03.pdf}}

@item [LoLA]
Karsten Schmidt. @b{@acronym{LoLA}: A Low Level Analyser}. Manual.
@footnote{@url{http://www.informatik.hu-berlin.de/top/lola/doku.ps}}

@item [Mar03]
Axel Martens. @b{Verteilte Gesch@"aftsprozesse -- Modellierung und Verifikation
mit Hilfe von Web Services} @i{(in German)}. PhD thesis, Humboldt-Universit@"at
zu Berlin, Mathematisch-Naturwissenschaftliche Fakult@"at II, 2003.

@item [MCK]
Javier Esparza, Claus Schr@"oter, and Stefan Schwoon. @b{Model-Checking Kit}.
@footnote{@url{http://www.fmi.uni-stuttgart.de/szs/tools/mckit}}

@item [MRS05]
Peter Massuthe, Wolfgang Reisig, and Karsten Schmidt. @b{An Operating Guideline
Approach to the SOA}. Proceedings of the 2nd South-East European Workshop on
Formal Methods 2005 (@acronym{SEEFM}05), Ohrid, Republic of Macedonia, 2005.
@footnote{@url{http://www.informatik.hu-berlin.de/top/download/publications/MassutheReisigSchmidt-OGApproach.ps}}

@item [PEP]
University of Oldenburg, Department of Computing Science. @b{@acronym{PEP,
Programming Environment based on Petri Nets}}. Manual.
@footnote{@url{http://parsys.informatik.uni-oldenburg.de/~pep}}

@item [Sch00]
Karsten Schmidt. @b{@acronym{LoLA}: A Low Level Analyser}. In: Mogens Nielsen,
and Dan Simpson, editors: @i{Application and Theory of Petri Nets, 21st
International Conference (@acronym{ICATPN} 2000)}, pp. 465-474, Springer-Verlag
(@acronym{LNCS} 1825), June 2000.

@item [SHS05]
Sebastian Hinz, Karsten Schmidt, and Christian Stahl. @b{Transforming BPEL to
Petri Nets}. In W.M.P. van der Aalst, B. Benatallah, F. Casati, and F. Curbera,
editors, @i{Proceedings of the Third International Conference on Business
Process Management (@acronym{BPM} 2005)}, pp. 220-235, Springer-Verlag
(@acronym{LNCS} 3649), September 2005.
@footnote{@url{http://www.informatik.hu-berlin.de/top/bpel2pn}}

@item [Sta05]
Christian Stahl. @b{A Petri Net Semantics for @acronym{BPEL}}.
Informatik-Berichte 188, Humboldt-Universit@"at zu Berlin, July 2005.
@footnote{@url{http://www.informatik.hu-berlin.de/Institut/struktur/systemanalyse/preprint/stahl188.pdf}}

@item [Wei04]
Daniela Weinberg. @b{Analyse der Bedienbarkeit}. Diplomarbeit,
Humboldt-Universit@"at zu Berlin, October 2004.
@footnote{@url{http://www.informatik.hu-berlin.de/top/download/publications/weinberg04.pdf}}

@item [WK02]
Michael Weber and Ekkart Kindler. @b{The Petri Net Markup Language}. In: Hartmut Ehrig,
Wolfgang Reisig, Grzegorz Rozenberg, Herbert Weber, editors: @i{Petri Net Technology for
Communication-Based Systems: Advances in Petri Nets}, pp. 124-144, Springer Verlag
(@acronym{LNCS} 2472), January 2003.@footnote{@url{http://www.informatik.hu-berlin.de/top/pnml/download/about/PNML_LNCS.pdf}}

@end table


@end ignore


@c ----------------------------------------------------------------------------

@include fdl.texi

@bye
