\input texinfo
@setfilename bpel2owfn
@include version.texi
@afourpaper
@finalout
@settitle GNU BPEL2oWFN Installation Manual

@c ----------------------------------------------------------------------------

@copying
@ifnotplaintext
@b{About this document:}

This manual describes the installation of GNU BPEL2oWFN, version
@value{VERSION}, a tool translating a web service described in
@acronym{BPEL} into open workflow net (@acronym{oWFN}), last updated
@value{UPDATED}.

Copyright @copyright{} 2005, 2006, 2007 Niels Lohmann

@quotation
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.2 or any later version
published by the Free Software Foundation; with no Invariant Sections, with the
Front-Cover Texts being ``A GNU Manual,'' and with the Back-Cover Texts as in
(a) below.  A copy of the license is included in the section entitled ``GNU Free
Documentation License.''

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.
@end quotation

Once GNU BPEL2oWFN is installed please read the User's
Manual which is part of the distribution or can be downloaded from the website
of GNU BPEL2oWFN, @url{http://www.gnu.org/software/bpel2owfn}.

@iftex
@image{images/tools4bpel,,0.4in}
@end iftex
@ifhtml
@image{images/tools4bpel}
@end ifhtml

GNU BPEL2oWFN is part of the Tools4@acronym{BPEL} project funded by
the Bundesministerium f@"ur Bildung und Forschung. See
@url{http://www.informatik.hu-berlin.de/top/tools4bpel} for details.
@end ifnotplaintext

@ifplaintext
@section Copyright
Copyright @copyright{} 2005, 2006, 2007 Niels Lohmann
@quotation
Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.
@end quotation

See @url{http://www.gnu.org/software/bpel2owfn} or the User's Manual for more information.
@end ifplaintext
@end copying

@c ----------------------------------------------------------------------------

@titlepage

@iftex
@title @image{images/bpel2owfn,,0.5in}
@end iftex

@ifnottex
@title GNU BPEL2oWFN
@end ifnottex

@subtitle Translating @acronym{BPEL} Processes into Open Workflow Nets
@subtitle GNU BPEL2oWFN Version @value{VERSION}, @value{UPDATED}
@vskip 4pt
@subtitle Installation Manual

@author Niels Lohmann

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c ----------------------------------------------------------------------------

@ifnottex
@node Top
@top GNU BPEL2oWFN
@insertcopying
@end ifnottex

@c ----------------------------------------------------------------------------

@menu
* Contents of this Distribution::
* Setup and Installation::
* Needed Programs::
* Change Log::
* Authors and Acknowledgements::
* GNU Free Documentation License::The license of this manual.
@end menu

@c ----------------------------------------------------------------------------

@contents
@paragraphindent none



@c ----------------------------------------------------------------------------

@ifplaintext
BEGIN OF README file for GNU BPEL2oWFN Version @value{VERSION}

@chapter About this Distribution
This file describes this distribution of GNU BPEL2oWFN, version
@value{VERSION}, a tool translating business processes described in
@acronym{BPEL} to open workflow nets (@acronym{oWFN}),
last updated @value{UPDATED}.

GNU BPEL2oWFN is licensed under the @acronym{GNU} General Public License.

Copyright @copyright{} 2005, 2006 Niels Lohmann and Christian Gierds.

GNU BPEL2oWFN is part of the Tools4@acronym{BPEL} project funded by the
Bundesministerium f@"ur Bildung und Forschung. See
@url{http://www.informatik.hu-berlin.de/top/tools4bpel} for details.
@end ifplaintext

@node Contents of this Distribution
@chapter Contents of this Distribution

@section Files
@table @code
@item AUTHORS
A list of the authors of GNU BPEL2oWFN, acknowledgements, and a contact
address.

@item ChangeLog
The change log listing all changes made during the distribution versions of
GNU BPEL2oWFN.

@item COPYING
The @acronym{GNU} General Public License (@acronym{GPL}) under which
GNU BPEL2oWFN is distributed.

@item INSTALL
Setup and Installation instructions and all information needed to bootstrap
GNU BPEL2oWFN.

@item NEWS
News concerning GNU BPEL2oWFN.

@item README
@ifplaintext
This file.
@end ifplaintext
@ifnotplaintext
A file describing the contents of the distribution.
@end ifnotplaintext
@end table

Moreover, the directory contains several files controlling the setup, build and
installation process. These files were generated by the @acronym{GNU}
Autotools.
@ifplaintext
For more information on the installation process refer to the @file{INSTALL}
file.
@end ifplaintext
@ifnotplaintext
For more information on the installation process see @ref{Setup and
Installation}.
@end ifnotplaintext


@section Directories

@table @code
@item src
The sources of GNU BPEL2oWFN. Each file contains a short documentation of
what it does as well as Doxygen-styled comments (see
@url{http://www.stack.nl/~dimitri/doxygen} for details).

@item doc
The documentation of GNU BPEL2oWFN consisting of a manual and
@ifnottex
an
@end ifnottex
@iftex
this
@end iftex
installation manual. The documentation is in Texinfo format and can be
converted into many file formats using @samp{make @var{format}} where
@samp{@var{format}} is a file format out of @samp{dvi}, @samp{html},
@samp{pdf} or @samp{ps}.

@item tests
Several test processes to self-test GNU BPEL2oWFN. The processes
@file{loan.bpel}, @file{purchase.bpel} and @file{shipping.bpel} were taken from
the @acronym{BPEL4WS} 1.1 specification.
@end table

@ifplaintext
@insertcopying

END OF README file for GNU BPEL2oWFN Version @value{VERSION}
@end ifplaintext




@c ----------------------------------------------------------------------------

@ifplaintext
BEGIN OF INSTALL file for BPEL2oWFN Version @value{VERSION}
@end ifplaintext

@node Setup and Installation
@chapter Setup and Installation

The distribution environment of GNU BPEL2oWFN was created using the
@acronym{GNU} Autotools. If you are familiar with the setup and installation
procedure of any @acronym{GNU} tool you may skip this section.

@section Setup
To setup the installation environment and to compile GNU BPEL2oWFN simply
follow these steps:

@enumerate
@item Unpack the source tarball by entering@footnote{Cygwin users should open a
@code{tcsh}-shell before.}

@smallexample
gunzip bpel2owfn-@value{VERSION}.tar.gz
tar xf bpel2owfn-@value{VERSION}.tar
@end smallexample

@item Enter that directory:
@smallexample
cd bpel2owfn-@value{VERSION}
@end smallexample

@item Run the configure shell script which attempts to guess correct values for
various system-dependent variables used during compilation. It uses those
values to create a @file{Makefile} in each directory of the package. Entering

@smallexample
./configure
@end smallexample

should lead to an output like:

@c @cartouche
@smallexample
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking build system type... i686-pc-cygwin
checking for style of include used by make... GNU
checking for g++... g++
checking for C++ compiler default output file name... a.exe
checking whether the C++ compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... .exe
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for inline... inline
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking dependency style of g++... (cached) gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking whether make sets $(MAKE)... (cached) yes
checking for a BSD-compatible install... /usr/bin/install -c
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for size_t... yes
checking for ANSI C header files... (cached) yes
checking assert.h usability... yes
checking assert.h presence... yes
checking for assert.h... yes
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking for unistd.h... (cached) yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for pow... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... no
checking for an ANSI C-conforming const... yes
checking for error_at_line... no
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for working alloca.h... yes
checking for alloca... yes
checking for memset... yes
checking for bison... bison -y
checking for flex... flex
checking for yywrap in -lfl... yes
checking lex output file root... lex.yy
checking whether yytext is a pointer... no
checking for kc++... kc++
checking for dot... dot
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating src/Makefile
config.status: creating tests/Makefile
config.status: creating src/bpel2owfn.h
config.status: executing depfiles commands
@end smallexample
@c @end cartouche

In some cases the configure script complains (i.e.@: warns) about tools which
could not be found in your system path. In this case please check
@ref{Needed Programs}. GNU BPEL2oWFN can be compiled without these tools.
However, you cannot make changes to large parts of the programm as you will not
be able to generate source files without the tools.

@item After all Makefiles are created, run

@smallexample
make
@end smallexample

to compile the executable binary as well as a documentation file.

@item Alternatively, you can run

@smallexample
make check
@end smallexample

to self-test the created binary. After many lines of output@footnote{Unless 
the testscript displays error messages warnings of GNU BPEL2oWFN can be
ignored.} @code{make check} should announce

@c @cartouche
@smallexample
==================
All 5 tests passed
==================
@end smallexample
@c @end cartouche

or, if anything went wrong, prints error message and requests to report the
encountered bug to @email{bug-bpel2owfn@@gnu.org}.
@end enumerate

@section Installation

@ignore
The compilation GNU BPEL2oWFN is controlled by several Makefiles. Make
sure that all required programs (see @ref{Required Programs}) are reachable in
your path. To compile GNU BPEL2oWFN, just run @samp{make}.
@end ignore

After successful compilation and self tests an executable file @file{bpel2owfn}
(or @file{bpel2owfn.exe} on systems running Microsoft Windows) is created in
the directory @file{bpel2owfn-@value{VERSION}/src} of the distribution. This
file has no dependencies to other files of the distribution and can be copied
to any directory.

Alternatively you can install GNU BPEL2oWFN properly by executing
@footnote{Usually, @samp{make install} and @samp{make uninstall} can only be
executed by the root user.}

@smallexample
make install
@end smallexample

to copy the binary to the directory @file{/usr/local/bin} and to make the
documentation accessible (i.e.@: copy it to @file{/usr/local/info}) for

@smallexample
info bpel2owfn
@end smallexample

You can undo the installation by entering

@smallexample
make uninstall
@end smallexample

The setup and installation procedure can be customized by running
@code{./configure} with several command-line options. Type

@smallexample
./configure --help
@end smallexample

for more information.


@section Problems during Setup or Installation

Any warning during an in other respects successful compilation can be
ignored --- these warnings mostly occur in generated files from Flex, Bison or
Kimwitu++ and are outside of our scope.

The compilation of GNU BPEL2oWFN was tested on several operating systems
such as Microsoft Windows (running Cygwin), @acronym{GNU}/Linux, Apple Mac OS X
and Sun Solaris. Anyway, if the compilation fails please make sure you use the
most recent (stable) versions of the @acronym{GNU} Compiler Collection. If this
does not help please send us an electronic mail to
@email{bug-bpel2owfn@@gnu.org}. Include the version number of your
distribution (version @value{VERSION} of @value{UPDATED}). Also include in your
message the output that the make process produced. We will try to answer your
mail within a week.

If you are not interested in compiling GNU BPEL2oWFN yourself you can
alternatively download executable binaries for several operating systems on the
website of GNU BPEL2oWFN (@url{http://www.gnu.org/software/bpel2owfn}).



@section Makefile Targets

The generated Makefiles serve different targets:

@table @code
@item all
Compile GNU BPEL2oWFN and create an executable binary @file{bpel2owfn}
(or @file{bpel2owfn.exe} on systems running Microsoft Windows) in the directory
@file{bpel2owfn-@value{VERSION}/src}.

@item dvi
@itemx html
@itemx pdf
@itemx ps
Generate documentation files in the given format which can be @acronym{DVI},
@acronym{HTML}, @acronym{PDF} or PostScript. The documentation is generated
in the directory @file{bpel2owfn-@value{VERSION}/doc} and is named
@file{bpel2owfn.@var{format}} (User's Manual).

@item clean
Clean all temporary files created during the compilation. Executables as well
as generated documentation are preserved.

@item distclean
Clean also source files generated by the compiler generator tools (Flex, Bison
and Kimwitu++). Executables as well as created documentation files are also
removed. Before re-compilation you have to run @samp{./configure} again. Please note
that afer running @samp{make distclean} you need the tools described in
@ref{Needed Programs} to compile.

@item check
Perform a number of self-tests: the directory @file{tests} contains several
@acronym{BPEL} processes which are read and compiled.

@ignore
@item pure-windows-executable
Create an executable binary which is independent of the Cygwin libraries. This
file can be executed on any system running Microsoft Windows, independently of
a Cygwin environment.
@end ignore

@end table

@c ----------------------------------------------------------------------------





@node Needed Programs
@chapter Needed Programs

@anchor{Required Programs}
@section Required Programs

To compile GNU BPEL2oWFN you do not need any specific program other than
the @acronym{GNU} Compiler Collection. If you however want to change the
program (e.g. add new Petri net patterns) you need the following programs to
generate source code. These programs are (as GNU BPEL2oWFN itself) free
software distributed under the @acronym{GNU} General Public License.


@table @asis
@item @b{Flex}, A fast scanner generator
Flex is needed to generate the lexer of GNU BPEL2oWFN. Flex was written
by Vern Paxon. Copyright @copyright{} 1990 The Regents of the University of
California. All rights reserved. Flex is available under
@url{http://www.gnu.org/software/flex/flex.html}.

@item @b{Bison}, The @acronym{YACC}-compatible Parser Generator
Bison is needed to generate the parser of GNU BPEL2oWFN. Bison was
written by Robert Corbett und Richard Stallman. Copyright @copyright{} 1992,
1998, 1999, 2003, 2004, 2005 Free Software Foundation, Inc. Bison is available
under @url{http://www.gnu.org/software/bison/bison.html}.

@item @b{Kimwitu++}, The Term Processor
Kimwitu++ is needed to generate all files managing the @acronym{AST, abstract
syntax tree}. Kimwitu++ was written by Toby Neumann and Michael Piefel.
Copyright @copyright{} 1988-1997  Axel Belinfante, University of Twente.
Copyright @copyright{} 1997-2003  Michael Piefel, Humboldt-University Berlin.
Kimwitu++ is available under
@url{http://site.informatik.hu-berlin.de/kimwitu++}.
@end table


@section Optional Programs

GNU BPEL2oWFN is a compiler and thus creating output files which can be
read by several other programs. These programs are not needed to compile
GNU BPEL2oWFN yet without these programs GNU BPEL2oWFN makes not
much sense.


@table @asis
@item @b{@acronym{LoLA}}, a Low Level Petri net Analyzer
@acronym{LoLA} is an explicit model checker implementing a broad variety of
reduction techniques such as partial order reduction, symmetries or the sweep
line method. @acronym{LoLA} was written by Karsten Schmidt and is available
under @url{http://www.informatik.hu-berlin.de/~kschmidt/lola.html}.

@c @item @b{The Model-Checking Kit}
@c The Model-Checking Kit is a collection of programs which allow to model a
@c finite-state system using a variety of modelling languages, and verify it using
@c a variety of checkers, including deadlock-checkers, reachability-checkers, and
@c model-checkers for the temporal logics CTL and LTL. The Model-Checking Kit is
@c maintained by Javier Esparza, Claus Schröter and Stefan Schwoon at the
@c University of Stuttgart and is available under
@c @url{http://www.fmi.uni-stuttgart.de/szs/tools/mckit}.


@item @b{Graphviz}, the Graph Visualization Software
Graphviz is a graph visualization software with several graph layout programs
including dot. Graphviz is maintained by AT&T Labs and is available under
@url{http://www.graphviz.org}.
@end table

The Graphviz tool dot can be used to create a graphical representation of the
generated Petri net in @acronym{PNG, Portable Network Graphic} format. If dot
is not found on your system, GNU BPEL2oWFN will only create a .dot-file
and does not try to invoke dot.



@section Reference System

As of @value{UPDATED-MONTH}, we use the following system developing and
building GNU BPEL2oWFN:

@itemize
@item Intel Pentium M processor, 1.60 GHz
@item 2 GB RAM
@item Microsoft Windows XP Home Edition Service Pack 2
@item Cygwin with cygwin.dll version 1.5.23-2
@item @acronym{GNU} Compiler Collection 3.4.4 (cygming special, gdc 0.12, using dmd 0.125)
@item Flex version 2.5.4
@item @acronym{GNU} Bison version 2.3
@item Kimwitu++ version 2.3.8
@end itemize

The version numbers are not to be understood as system requirements, but as a
help if you fail to compile the sources.


@ifplaintext
@insertcopying

END OF INSTALL file for BPEL2oWFN Version @value{VERSION}
@end ifplaintext


@c ----------------------------------------------------------------------------

@ifplaintext
BEGIN OF ChangeLog file for BPEL2oWFN Version @value{VERSION}
@end ifplaintext

@node Change Log
@chapter Change Log

Most recent version at the end of this section.



@unnumberedsubsec Version 1.0 (16 January 2006)
@itemize --
@item input:
@itemize
@item @acronym{BPEL} process compliant to the specificiation
@acronym{BPEL4WS} version 1.1, May 2003.
@end itemize

@item output:
@itemize
@item @acronym{LoLA} Petri net
@item open workflow net
@item Dot representation
@end itemize

@item implemented patterns:
@itemize 
@item Christian Stahl. @i{A Petri Net Semantics for
@acronym{BPEL}}. Informatik-Berichte 188, Humboldt-Universit@"at zu Berlin,
July 2005.
@end itemize
@end itemize



@unnumberedsubsec Version 1.1 (24 February 2006)
@itemize --
@item new output formats:
@itemize
@item @acronym{APNN, Abstract Petri Net Notation} Petri net
@item @acronym{PNML, Petri Net Markup Language} Petri net
@item low-level @acronym{PEP, Programming Environment based on Petri Nets} Petri
net
@end itemize

@item overworked patterns:
@itemize 
@item the Stahl-semantics (see version 1.0) has been enhanced and can be
parametrized:
@itemize
@item original semantics
@item models without BPEL's standard faults
@item acyclic models
@end itemize
For more information please refer to the User's Manual.
@end itemize

@item static analysis:
@itemize
@item To reduce the size of the Petri net model static analysis is used to only
generate nodes for the @acronym{DPE, dead path elimination} when necessary.
@end itemize

@item miscellaneous:
@itemize
@item The compiler generator tools Flex, Bison and Kimwitu++ are not any more
necessary to compile GNU BPEL2oWFN: the generated sources are now part of
the distrubution.
@item The @acronym{oWFN} format was overworked and allows final markings.
@item @acronym{GNU} getopt allows more flexible command-line parameter
processing allowing to create several output file formats in a single run.
@item Debug output can be written into a log file.
@item The classes organizing the Petri nets are overworked for performance and
extensibility.
@end itemize

@item fixed bugs:
@itemize
@item The generation of all possible types of the @code{<invoke>} activity
(synchronous, asynchronous, with and without implicit scope) is overworked.
@end itemize
@end itemize



@unnumberedsubsec Version 1.2 (6 April 2006)
@itemize --

@item overworked patterns:
@itemize 
@item more parameterized versions of the Stahl-semantics (see version 1.1):
@itemize
@item acyclic models (also acyclic event handlers)
@item models without variables
@item models without standard faults occuring while handling a fault
@end itemize
For more information please refer to the User's Manual.
@end itemize


@item static analysis:
@itemize 
@item A control flow graph can be built and used to detect the use of uninitialized
variables.
@end itemize

@item miscellaneous:
@itemize
@item The command-line parameter @samp{-p finishloop} is renamed to @samp{-p finalloop}.
@item Structural reduction rules remove all structural dead nodes of the generated Petri
net model.
@end itemize


@item fixed bugs:
@itemize 
@item Pattern of asynchronous @code{<invoke>} activity does no longer receive messages.
@item Structural reduction rules no longer change the semantics of the @code{<switch>}
activity.
@item Structural reduction rules no longer remove the loop transition for deadlock search.
@end itemize
@end itemize

@unnumberedsubsec Version 2.0 (6 December 2006)
@itemize --

@item miscellaneous:
@itemize 
@item overworked architecture
@end itemize


@end itemize


@ifplaintext
@insertcopying

END OF ChangeLog file for BPEL2oWFN Version @value{VERSION}
@end ifplaintext


@c ----------------------------------------------------------------------------

@ifplaintext
BEGIN OF AUTHORS file for BPEL2oWFN Version @value{VERSION}
@end ifplaintext

@node Authors and Acknowledgements
@chapter Authors and Acknowledgements

@section Authors

GNU BPEL2oWFN was written by:
@itemize
@item Niels Lohmann, @i{Humboldt-Universit@"at zu Berlin}
@item Christian Gierds, @i{Humboldt-Universit@"at zu Berlin}
@item Martin Znamirowski, @i{Humboldt-Universit@"at zu Berlin}
@end itemize

The Petri net patterns were created by:
@itemize
@item Christian Stahl, @i{Humboldt-Universit@"at zu Berlin} (BPEL4WS 1.1)
@item Niels Lohmann, @i{Humboldt-Universit@"at zu Berlin} (WS-BPEL 2.0)
@end itemize


@section Acknowledgements

We would like to thank:
@itemize
@item Sylvain Beucler, @i{GNU Project}@*
for his help moving BPEL2oWFN to Savannah
@item Maarten Boote, @i{Technische Universiteit Eindhoven}@*
for integrating BPEL2oWFN to LaQuSo
@item Jan Bretschneider, @i{Humboldt-Universit@"at zu Berlin}@*
for patient C++ help
@item Dirk Fahland, @i{Humboldt-Universit@"at zu Berlin}@*
for fruitful discussions about BPEL's semantics
@item Carsten Frenkler, @i{Gedilan Technologies}@*
for challenging @acronym{BPEL} processes
@item Mario Karrenbrock, @i{FH Wilhelmshaven/SAP}@*
for finding bugs
@item Dieter K@"onig, @i{IBM}@*
for valuable advice concerning @acronym{BPEL}
@item Oliver Kopp, @i{Universit@"at Stuttgart}@*
for challenging @acronym{BPEL} processes
@item Axel Martens, @i{IBM}@*
for valuable advice concerning @acronym{BPEL}
@item Simon Moser, @i{IBM}@*
for valuable advice concerning @acronym{BPEL}
@item Michael Piefel, @i{Humboldt-Universit@"at zu Berlin}@*
for help with Kimwitu++
@item Dennis Reinert, @i{Humboldt-Universit@"at zu Berlin}@*
for his work on the first versions of BPEL2oWFN
@item Eric Verbeek, @i{Technische Universiteit Eindhoven}@*
for integrating BPEL2oWFN to the ProM framework and valuable comments on BPEL's link semantics
@item Jan Martijn van der Werf, @i{Technische Universiteit Eindhoven}@*
for his discussion about the PNML-oWFN format
@end itemize

GNU BPEL2oWFN is part of the Tools4@acronym{BPEL} project funded by the
German Bundesministerium f@"ur Bildung und Forschung.

@section Contact Person
Niels Lohmann

Humboldt-Universit@"at zu Berlin@*
Institut f@"ur Informatik@*
Unter den Linden 6@*
10099 Berlin, Germany

@table @asis
@itemx Homepage
@url{http://www.informatik.hu-berlin.de/top/mitarbeiter/lohmann}

@itemx E-mail
@email{nlohmann@@informatik.hu-berlin.de}

@itemx Phone
(+49) (30) 2093-3070

@itemx Fax
(+49) (30) 2093-3067
@end table

@ifplaintext
@insertcopying

END OF AUTHORS file for BPEL2oWFN Version @value{VERSION}
@end ifplaintext

@c ----------------------------------------------------------------------------

@include fdl.texi

@bye
