\input texinfo
@setfilename bpel2owfn
@include version.texi
@afourpaper
@finalout
@settitle @acronym{BPEL2oWFN} Installation Manual

@c ----------------------------------------------------------------------------

@copying
@ifhtml
@image{images/bpel2owfn}
@end ifhtml

This manual describes the installation of @acronym{BPEL2oWFN}, Version
@value{VERSION}, a tool translating business processes described in
@acronym{BPEL} to open workflow nets (@acronym{oWFN}),
last updated @value{UPDATED}.

Copyright @copyright{} 2005, 2006 Niels Lohmann

Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.

@acronym{BPEL2oWFN} is licensed under the @acronym{GNU} General Public License.

Copyright @copyright{} 2005, 2006 Niels Lohmann, Christian Gierds and Dennis
Reinert.

@iftex
@image{images/tools4bpel,,0.4in}
@end iftex

@ifhtml
@image{images/tools4bpel}
@end ifhtml

@acronym{BPEL2oWFN} is part of the Tools4@acronym{BPEL} project funded by the
Bundesministerium f@"ur Bildung und Forschung.

@end copying

@c ----------------------------------------------------------------------------

@titlepage

@iftex
@title @image{images/bpel2owfn,,0.5in}
@end iftex

@ifnottex
@title @acronym{BPEL2oWFN}
@end ifnottex

@subtitle Translating @acronym{BPEL} Processes to Open Workflow Nets
@subtitle @acronym{BPEL2oWFN} Version @value{VERSION}, @value{UPDATED}
@vskip 4pt
@subtitle Installation Manual

@author Niels Lohmann

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c ----------------------------------------------------------------------------

@ifnottex
@node Top
@top @acronym{BPEL2oWFN}
@insertcopying
@end ifnottex

@c ----------------------------------------------------------------------------

@menu
* Contents of this Distribution::
* Setup and Installation::
* Needed Programs::
* Change Log::
* Authors and Acknowledgements::
@end menu

@c ----------------------------------------------------------------------------

@contents
@paragraphindent none



@c ----------------------------------------------------------------------------

@ifplaintext
BEGIN OF README file for BPEL2oWFN Version @value{VERSION}
@end ifplaintext

@node Contents of this Distribution
@chapter Contents of this Distribution

@section Files
@table @code
@item AUTHORS
A list of all authors of @acronym{BPEL2oWFN} as well as acknowledgements.

@item CHANGES
The change log listing all changes made during the distribution versions of
@acronym{BPEL2oWFN}.

@item COPYING
The @acronym{GNU} General Public License (@acronym{GPL}) under which
@acronym{BPEL2oWFN} is distributed. The @acronym{GPL} is also a chapter of the
manual.

@item INSTALL
Setup and Installation instructions and all information needed to bootstrap
@acronym{BPEL2oWFN}.

@item Makefile
The Makefile controlling the compilation of @acronym{BPEL2oWFN} and the
generation of the documentation.

@item README
A file describing the contents of the distribution.
@end table



@section Directories

@table @code
@item src
The sources of @acronym{BPEL2oWFN}. Files ending with @samp{.k} are Kimwitu++
source files. Each file contains a short documentation of what it does as well
as Doxygen-styled comments (see @url{http://www.stack.nl/~dimitri/doxygen} for
details).

@item doc
The documentation of @acronym{BPEL2oWFN} consisting of a manual and
@ifnottex
an
@end ifnottex
@iftex
this
@end iftex
installation manual. The documentation is in Texinfo format and can be compiled
using @samp{make}.

@item test
Several test processes to self-test @acronym{BPEL2oWFN}. The processes
@file{loan.bpel}, @file{purchase.bpel} and @file{shipping.bpel} were taken from
the @acronym{BPEL4WS} 1.1 specification.
@end table

@ifplaintext
END OF README file for BPEL2oWFN Version @value{VERSION}
@end ifplaintext




@c ----------------------------------------------------------------------------

@ifplaintext
BEGIN OF INSTALL file for BPEL2oWFN Version @value{VERSION}
@end ifplaintext

@node Setup and Installation
@chapter Setup and Installation

@section Compilation
Compile @acronym{BPEL2oWFN} is controlled by several Makefiles. Make sure that
all required programs (see @ref{Required Programs}) are reachable in your
path. To compile @acronym{BPEL2oWFN}, just run @samp{make}. After successful
compilation an executable file @file{bpel2owfn} (or @file{bpel2owfn.exe} on
systems running Microsoft Windows) is created in the directory
@file{@value{FILENAME}/src} of the distribution. This file has no dependencies
to other files of the distribution and can be copied to any directory.

Any warning during an in other respects successful compilation can be
ignored---these warnings mostly occur in generated files from Flex, Bison or
Kimwitu++ and are outside of our scope.

@acronym{BPEL2oWFN} was tested on several operating systems such as Microsoft
Windows (running cygwin), Linux and Sun OS. Anyway, if the compilation fails
please make sure you use the most recent versions of the @acronym{GNU}
Compiler Collection, Flex, Bison and Kimwitu++. If this does not help please
send us an electronic mail to @email{nlohmann@@informatik.hu-berlin.de}.
Include the version number of your distribution (version @value{VERSION} of
@value{UPDATED}). Also include in your message the output that the make process
produced. We will try to answer your mail within a week.

If you are not interested in compiling @acronym{BPEL2oWFN} yourself you can
alternatively download executable binaries for several operating systems on the
website of @acronym{BPEL2oWFN}
(@url{www.informatik.hu-berlin.de/top/forschung/projekte/tools4bpel/bpel2owfn}).

@section Makefile Targets

@table @code
@item all
Compile @acronym{BPEL2oWFN} and create an executable binary @file{bpel2owfn}
(or @file{bpel2owfn.exe} on systems running Microsoft Windows) in the directory
@file{@value{FILENAME}/src}.

@item dvi
@itemx html
@itemx pdf
@itemx ps
@itemx info
Generate documentation files in the given format which can be @acronym{DVI},
@acronym{HTML}, @acronym{PDF}, PostScript or @acronym{GNU} Info. The
documentation is generated in the directory @file{@value{FILENAME}/doc} and
is named @file{bpel2owfn.@var{format}} (User's Manual) and
@file{install.@var{format}} (Installation Manual), resp.

@item clean
Clean all temporary files created during the compilation. Executables as well
as generated documentation are preserved.

@item distclean
Clean everything that does not belong to the distribution, i.e. any file
created during compilation. Executables as well as created documentation files
are also removed.

@item check
Perform a number of self-tests: the directory @file{test} contains several
@acronym{BPEL} processes which are processed.

@item dist
Create a zipped distribution tar file containing all files of the distribution
(calls @samp{distclean} before).
@end table


@c ----------------------------------------------------------------------------





@node Needed Programs
@chapter Needed Programs

@anchor{Required Programs}
@section Required Programs

To compile @acronym{BPEL2oWFN} you need the following programs. These programs
are (as @acronym{BPEL2oWFN} itself) free software distributed under the
@acronym{GNU} General Public License.


@table @asis
@item @b{Flex}, A fast scanner generator
Flex is needed to generate the lexer of @acronym{BPEL2oWFN}. Flex was written
by Vern Paxon. Copyright @copyright{} 1990 The Regents of the University of
California. All rights reserved. Flex is available under
@url{http://www.gnu.org/software/flex/flex.html}.

@item @b{Bison}, The YACC-compatible Parser Generator
Bison is needed to generate the parser of @acronym{BPEL2oWFN}. Bison was
written by Robert Corbett und Richard Stallman. Copyright @copyright{} 1992,
1998, 1999, 2003, 2004, 2005 Free Software Foundation, Inc. Bison is available
under @url{http://www.gnu.org/software/bison/bison.html}.

@item @b{Kimwitu++}, The Term Processor
Kimwitu++ is needed to generate all files managing the @acronym{AST, abstract
syntax tree}. Kimwitu++ was written by Toby Neumann and Michael Piefel.
Copyright @copyright{} 1988-1997  Axel Belinfante, University of Twente.
Copyright @copyright{} 1997-2000  Michael Piefel, Humboldt-University Berlin.
Kimwitu++ is available under
@url{http://site.informatik.hu-berlin.de/kimwitu++}.
@end table


@section Optional Programs

@acronym{BPEL2oWFN} is a compiler and thus creating output files which can be
read by several other programs. These programs are not needed to compile
@acronym{BPEL2oWFN} yet without these programs @acronym{BPEL2oWFN} makes not
much sense.


@table @asis
@item @b{@acronym{LoLA}}, a Low Level Petri net Analyzer
@acronym{LoLA} is an explicit model checker implementing a broad variety of
reduction techniques such as partial order reduction, symmetries or the sweep
line method. @acronym{LoLA} was written by Karsten Schmidt and is available
under @url{http://www.informatik.hu-berlin.de/~kschmidt/lola.html}.

@item @b{Graphviz}, the Graph Visualization Software
Graphviz is a graph visualization software with several graph layout programs
including dot. Graphviz is maintained by AT&T Labs and is available under
@url{http://www.graphviz.org}.
@end table

@ifplaintext
END OF INSTALL file for BPEL2oWFN Version @value{VERSION}
@end ifplaintext




@c ----------------------------------------------------------------------------

@ifplaintext
BEGIN OF CHANGES file for BPEL2oWFN Version @value{VERSION}
@end ifplaintext

@node Change Log
@chapter Change Log

@table @b
@item Version 1.0 (16.01.2006)
@itemize --
@item initial release
@end itemize
@end table

@ifplaintext
END OF CHANGES file for BPEL2oWFN Version @value{VERSION}
@end ifplaintext


@c ----------------------------------------------------------------------------

@ifplaintext
BEGIN OF AUTHORS file for BPEL2oWFN Version @value{VERSION}
@end ifplaintext

@node Authors and Acknowledgements
@chapter Authors and Acknowledgements

@section Authors

@acronym{BPEL2oWFN} was written by:
@itemize
@item Niels Lohmann (Humboldt-Universit@"at zu Berlin)
@item Christian Gierds (Humboldt-Universit@"at zu Berlin)
@item Dennis Reinert (Humboldt-Universit@"at zu Berlin)
@end itemize

The Petri net patterns were created by:
@itemize
@item Christian Stahl (Humboldt-Universit@"at zu Berlin)
@end itemize

@section Acknowledgements

We would like to thank:
@itemize
@item Simon Moser (IBM) for valuable advice concerning @acronym{BPEL}
@item Michael Piefel (Humboldt-Universit@"at zu Berlin) for help with Kimwitu++
@item Oliver Kopp (Universit@"at Stuttgart) for challenging @acronym{BPEL}
processes
@end itemize

@acronym{BPEL2oWFN} is part of the Tools4@acronym{BPEL} project funded by the
Bundesministerium f@"ur Bildung und Forschung.

@section Contact Person
Niels Lohmann

Humboldt-Universit@"at zu Berlin@*
Institut f@"ur Informatik@*
Unter den Linden 6@*
10099 Berlin, Germany

@table @asis
@itemx Homepage
@url{http://www.informatik.hu-berlin.de/top/mitarbeiter/lohmann}

@itemx E-mail
@email{nlohmann@@informatik.hu-berlin.de}

@itemx Phone
(+49) (30) 2093 3070
@end table

@ifplaintext
END OF AUTHORS file for BPEL2oWFN Version @value{VERSION}
@end ifplaintext

@bye
