\input texinfo
@setfilename wendy.info
@include version.texi
@afourpaper
@finalout
@settitle Wendy User's Manual

@c --------------------------------------------------------------------------

@copying

@b{About this document:}

This manual is for Wendy, version @value{VERSION}, a tool to calculate operating guidelines, last updated @value{UPDATED}.

Copyright @copyright{} 2009 Niels Lohmann

@quotation
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.3 or any later version published by the Free Software Foundation; with no Invariant Sections, with the Front-Cover Texts being ``A GNU Manual,'' and with the Back-Cover Texts as in (a) below.  A copy of the license is included in the section entitled ``GNU Free Documentation License.''

(a) The FSF's Back-Cover Text is: ``You are free to copy and modify this GNU Manual. Buying copies from GNU Press supports the FSF in developing GNU and promoting software freedom.''
@end quotation
@end copying

@dircategory service-technology.org
@direntry
* wendy: (wendy).       Wendy.
@end direntry


@c --------------------------------------------------------------------------

@titlepage

@title Wendy

@subtitle Calculating Operating Guidelines
@subtitle @url{http://service-technology.org/wendy}
@vskip 0.5em
@subtitle Version @value{VERSION}, @value{UPDATED}

@author Niels Lohmann
@page


@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c --------------------------------------------------------------------------

@ifnottex
@node Top
@top Wendy
@insertcopying
@end ifnottex

@c --------------------------------------------------------------------------

@menu
* First Steps::How to set up and install Wendy.
* Command Line Options::How to run Wendy.
* Exit and Error Codes::What the error and exit codes of Wendy mean.
* ChangeLog::Version history.
* GNU Free Documentation License::The license of this manual.
@end menu

@c --------------------------------------------------------------------------

@contents
@paragraphindent none

@c --------------------------------------------------------------------------

@node First Steps
@chapter First Steps

@section Setup and Installation

@enumerate
@item Go to @url{http://service-technology.org/files/wendy} and download the latest release version of Wendy, say @file{wendy-@value{VERSION}.tar.gz}. To setup and compile Wendy, change into your download directory and type

@cartouche
@smallexample
tar xfz wendy-@value{VERSION}.tar.gz
cd wendy-@value{VERSION}
./configure
make
@end smallexample
@end cartouche

After compilation, a binary @samp{src/wendy} is generated.@footnote{On Microsoft Windows, the file will be called @file{wendy.exe}.} If you experience any compiler warnings, don't panic: Wendy contains some generated or third party code that we cannot influence.

@item To test whether everything went fine, type

@cartouche
@smallexample
make check
@end smallexample
@end cartouche

to execute the testcases located in @file{tests}. If everything went fine, you should see something like:@footnote{Some tests use Fiona to check whether the calculated operating guidelines are correct. If Fiona was not found by the configure script, theses tests are skipped.}

@smallexample
===================
All 12 tests passed
===================
@end smallexample

If an error occurs, please send the output to @email{wendy@@service-technology.org}.

@item To install the binary, the manpage, and the documentation, type

@cartouche
@smallexample
make install
@end smallexample
@end cartouche

You might need superuser permissions to do so.
@end enumerate

If you need any further information, see file @file{INSTALL} for detailed instructions.


@section Contents of the Distribution

The distribution contains several directories:

@table @file
@item doc
The Texinfo documentation of Wendy. The documentation can be created using @samp{make pdf}. Note you need to have Wendy properly installed before (see installation description above).

@item libs
The Petri Net API used by Wendy to parse and organize the open net.

@item man
The manpage of Wendy which can be displayed using @samp{man wendy} after having Wendy installed (see installation description above).

@item src
The source code of Wendy.

@item tests
Testcases for Rachel which check the generated binary. Some test scripts use Fiona to check whether the calculated operating guidelines are correct. If Fiona was not found by the configure script, theses tests are skipped.
@end table




@c --------------------------------------------------------------------------


@node Command Line Options
@chapter Invoking Wendy

Wendy is a command line tool and does not come with a fancy @acronym{GUI}. However, Wendy can be easily scripted and combined with other tools.

@section Command Line Options

For an overview of the command line options, type @samp{wendy -h} to see the following help screen:

@smallexample
@include cmdline.out
@end smallexample



@c --------------------------------------------------------------------------


@node Exit and Error Codes
@chapter Exit and Error Codes


@section Exit Codes

Wendy will exit with code @samp{0} in case everything went fine. That is, the command-line parameters were valid, the input open net could be read, the reachability graph of the inner could be build, the operating guidelines could be calculated, and---if requested---output files could be successfully written. In case any error occurs, the exit code will be @samp{1} and an error message with an error code (see below) will be printed to the standard error stream.

Note that Wendy's exit code is @b{not} related to the result of the controllability result. The messages

@smallexample
@cartouche
wendy: net is controllable: YES
@end cartouche
@end smallexample

and

@smallexample
@cartouche
wendy: net is controllable: NO
@end cartouche
@end smallexample

both yield exit code @samp{0} (successful termination).


@section Error Codes

In case any error occurs, Wendy aborts with exit code @samp{1} and prints a message with an error code to the standard error stream.

@table @asis
@item #01
Error opening the input open net or input file not found.

@smallexample
@cartouche
wendy: could not open file `foo.owfn' -- aborting [#01]
@end cartouche
@end smallexample

@item #02
Error parsing the input open net. Usually indicates the line of the error and some more or less helpful message on the parse error.

@smallexample
@cartouche
wendy:13: error near `Place': syntax error, unexpected IDENT,
          expecting KEY_INTERFACE or KEY_PLACE -- aborting [#02]
@end cartouche
@end smallexample

@item #03
The input open net is not normal. That is, it contains a transition that is connected to more than one interface place. Note that non-normal open net can be normalized using the frontend tool @samp{petri} of the Petri Net API.

@smallexample
@cartouche
wendy: the input open net must be normal -- aborting [#03]
@end cartouche
@end smallexample

@item #04
At most one file can be read at once. If no input filename is given, the open net is read from standard input.

@smallexample
@cartouche
wendy: at most one input file must be given -- aborting [#04]
@end cartouche
@end smallexample

@item #05
Wendy uses LoLA to build the reachability graph of the inner of the net. The configure script tries to find the executable @file{lola-full} in the system's path. If it was not found in the path, the executable must be given using the command-line option @samp{--lola}.

@smallexample
@cartouche
wendy: LoLA executable was not found -- aborting [#05]
@end cartouche
@end smallexample

@item #06
This error occurs in case Wendy could not parse the reachability graph from LoLA. This might happen if a wrong version of LoLA (e.g., not using the @samp{FULL} mode) is used or LoLA runs out of memory. To get the exact parse error, use the command-line option @samp{--verbose}.

@smallexample
@cartouche
wendy: error while parsing the reachability -- aborting [#06]
@end cartouche
@end smallexample

@item #07
A wrong command-line parameter was given or there was a problem with the combination of command-line parameters. This message is usually accompanied by another message describing the exact problem. Run @samp{wendy --help} for an overview of the valid command-line parameters.

@smallexample
@cartouche
wendy: `--showEmptyNode' option depends on option `dot'
wendy: invalid command-line parameter(s) -- aborting [#07]
@end cartouche
@end smallexample

@item #08
The report frequency for built knowledges must be a positive number. To switch off reporting at all, use @samp{--reportFrequency=0}.

@smallexample
@cartouche
wendy: report frequency must not be negative -- aborting [#08]
@end cartouche
@end smallexample

@item #09
Interface markings are stored in byte vectors, so the marking of each place has to be stored in one byte. Hence, the message bound must not exceed 255.

@smallexample
@cartouche
wendy: message bound must be between 1 and 255 -- aborting [#09]
@end cartouche
@end smallexample

@end table



@c --------------------------------------------------------------------------


@node ChangeLog
@chapter Version History

Wendy is developed under the ``Release Early, Release Often'' maxime (see @url{http://catb.org/~esr/writings/cathedral-bazaar/cathedral-bazaar/ar01s04.html}): Whenever enough integrated or a non-trivial changes have summed up, a new version is published. Though this releases might now always mark significant changes, they at least allow to quickly fix bugs and avoid infinite procrastination.

@include ChangeLog.texi

@sp 3

The most recent change log is available at Wendy's website at @url{http://service-technology.org/files/wendy/ChangeLog}.



@c --------------------------------------------------------------------------

@node GNU Free Documentation License
@appendix The GNU Free Documentation License

@include fdl.texi

@bye
