\input texinfo
@setfilename linda.info
@include version.texi
@afourpaper
@finalout
@settitle Linda User's Manual

@c --------------------------------------------------------------------------

@copying

@b{About this document:}

This manual is for linda, version @value{VERSION}, a tool to compute profiles for open nets, last updated @value{UPDATED}.

Copyright @copyright{} 2009 Jan Suermeli

@quotation
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.3 or any later version published by the Free Software Foundation; with no Invariant Sections, with the Front-Cover Texts being ``A GNU Manual,'' and with the Back-Cover Texts as in (a) below.  A copy of the license is included in the section entitled ``GNU Free Documentation License.''

(a) The FSF's Back-Cover Text is: ``You are free to copy and modify this GNU Manual. Buying copies from GNU Press supports the FSF in developing GNU and promoting software freedom.''
@end quotation
@end copying

@dircategory service-technology.org
@direntry
* linda: (linda).       linda.
@end direntry


@c --------------------------------------------------------------------------

@titlepage

@title Linda

@subtitle Computing Profiles for Open Nets
@subtitle @url{http://service-technology.org/linda}
@vskip 0.5em
@subtitle Version @value{VERSION}, @value{UPDATED}

@author Jan Suermeli
@page


@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c --------------------------------------------------------------------------

@ifnottex
@node Top
@top linda
@insertcopying
@end ifnottex

@c --------------------------------------------------------------------------

@menu
* First Steps::How to set up and install Linda.
* Command Line Options::How to run Linda.
* ChangeLog::Version history.
* GNU Free Documentation License::The license of this manual.
@end menu

@c --------------------------------------------------------------------------

@contents
@paragraphindent none

@c --------------------------------------------------------------------------

@node First Steps
@chapter First Steps

@section Setup and Installation

@enumerate
@item Go to @url{http://service-technology.org/files/linda} and download the latest release version of linda, say @file{linda-@value{VERSION}.tar.gz}. To setup and compile linda, change into your download directory and type

@cartouche
@smallexample
tar xfz linda-@value{VERSION}.tar.gz
cd linda-@value{VERSION}
./configure
make
@end smallexample
@end cartouche

After compilation, a binary @samp{src/linda} is generated.@footnote{On Microsoft Windows, the file will be called @file{linda.exe}.} If you experience any compiler warnings, don't panic: linda contains some generated or third party code that we cannot influence.


If an error occurs, please send the output to @email{linda@@service-technology.org}.

@item To install the binary, the manpage, and the documentation, type

@cartouche
@smallexample
make install
@end smallexample
@end cartouche

You might need superuser permissions to do so.
@end enumerate

If you need any further information, see file @file{INSTALL} for detailed instructions.

@c --------------------------------------------------------------------------


@node Command Line Options
@chapter Invoking linda

linda is a command line tool and does not come with a fancy @acronym{GUI}. However, linda can be easily scripted and combined with other tools.

@section Command Line Options

For an overview of the command line options, type @samp{linda -h} to see the following help screen:

@smallexample
@verbatiminclude cmdline.out
@end smallexample


@c --------------------------------------------------------------------------


@node ChangeLog
@chapter Version History

linda is developed under the ``Release Early, Release Often'' maxime (see @url{http://catb.org/~esr/writings/cathedral-bazaar/cathedral-bazaar/ar01s04.html}): Whenever enough integrated or a non-trivial changes have summed up, a new version is published. Though this releases might not always mark significant changes, they at least allow to quickly fix bugs and avoid infinite procrastination.

@include ChangeLog.texi

@sp 3

The most recent change log is available at linda's website at @url{http://service-technology.org/files/linda/ChangeLog}.


@c --------------------------------------------------------------------------

@node GNU Free Documentation License
@appendix The GNU Free Documentation License

@include fdl.texi

@bye
