\input texinfo
@setfilename marlene.info
@include version.texi
@afourpaper
@finalout
@settitle Marlene User's Manual

@c --------------------------------------------------------------------------

@copying

@b{About this document:}

This manual is for Marlene, version @value{VERSION}, a tool to synthesize behavioral adapters, last updated @value{UPDATED}.

Copyright @copyright{} 2009 Christian Gierds

@quotation
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.3 or any later version published by the Free Software Foundation; with no Invariant Sections, with the Front-Cover Texts being ``A GNU Manual,'' and with the Back-Cover Texts as in (a) below.  A copy of the license is included in the section entitled ``GNU Free Documentation License.''

(a) The FSF's Back-Cover Text is: ``You are free to copy and modify this GNU Manual. Buying copies from GNU Press supports the FSF in developing GNU and promoting software freedom.''
@end quotation
@end copying

@dircategory service-technology.org
@direntry
* marlene: (marlene).       Marlene.
@end direntry


@c --------------------------------------------------------------------------

@titlepage

@title Marlene

@subtitle Synthesizing Behavioral Adapters
@subtitle @url{http://service-technology.org/marlene}
@vskip 0.5em
@subtitle Version @value{VERSION}, @value{UPDATED}

@author Christian Gierds
@page


@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c --------------------------------------------------------------------------

@ifnottex
@node Top
@top Marlene
@insertcopying
@end ifnottex

@c --------------------------------------------------------------------------

@menu
* First Steps::How to set up and install Marlene.
* Command Line Options::How to run Marlene.
* Exit and Error Codes::What the error and exit codes of Marlene mean.
* ChangeLog::Version history.
* GNU Free Documentation License::The license of this manual.
@end menu

@c --------------------------------------------------------------------------

@contents
@paragraphindent none

@c --------------------------------------------------------------------------

@node First Steps
@chapter First Steps

@section Setup and Installation

@enumerate
@item Go to @url{http://service-technology.org/files/marlene} and download the latest release version of Marlene, say @file{marlene-@value{VERSION}.tar.gz}. To setup and compile Marlene, change into your download directory and type

@cartouche
@smallexample
tar xfz marlene-@value{VERSION}.tar.gz
cd marlene-@value{VERSION}
./configure
make
@end smallexample
@end cartouche

After compilation, a binary @samp{src/marlene} is generated.@footnote{On Microsoft Windows, the file will be called @file{marlene.exe}.} If you experience any compiler warnings, don't panic: Marlene contains some generated or third party code that we cannot influence.

@item To test whether everything went fine, type

@cartouche
@smallexample
make check
@end smallexample
@end cartouche

to execute the testcases located in @file{tests}. If everything went fine, you should see something like:@footnote{Some tests use Fiona to check whether the calculated operating guidelines are correct. If Fiona was not found by the configure script, theses tests are skipped.}

@smallexample
===================
All ?? tests passed
===================
@end smallexample

If an error occurs, please send the output to @email{marlene@@service-technology.org}.

@item To install the binary, the manpage, and the documentation, type

@cartouche
@smallexample
make install
@end smallexample
@end cartouche

You might need superuser permissions to do so.
@end enumerate

If you need any further information, see file @file{INSTALL} for detailed instructions.


@section Contents of the Distribution

The distribution contains several directories:

@table @file
@item doc
The Texinfo documentation of Marlene. The documentation can be created using @samp{make pdf}. Note you need to have Marlene properly installed before (see installation description above).

@item libs
The Petri Net @acronym{API} used by Marlene to parse and organize the open net.

@item man
The manpage of Marlene which can be displayed using @samp{man marlene} after having Marlene installed (see installation description above).

@item src
The source code of Marlene.

@item tests
Testcases for Marlene which check the generated binary. Some test scripts use Fiona to check whether the calculated operating guidelines are correct. If Fiona was not found by the configure script, theses tests are skipped.
@end table




@c --------------------------------------------------------------------------


@node Command Line Options
@chapter Invoking Marlene


@section Command Line Options

For an overview of the command line options, type @samp{marlene -h} to see the following help screen:

@smallexample
@include cmdline.out
@end smallexample



@section Compatibility to Fiona




@c --------------------------------------------------------------------------


@node Exit and Error Codes
@chapter Exit and Error Codes


@section Exit Codes

@itemize

@item 0 -- adapter (or controller/engine) was built successfully
@item >0 -- adapter could not be built

@end itemize

@section Error Codes

@itemize

@item 2 -- wrong command line command line parameter

@end itemize



@c --------------------------------------------------------------------------


@node ChangeLog
@chapter Version History

Marlene is developed under the ``Release Early, Release Often'' maxime (see @url{http://catb.org/~esr/writings/cathedral-bazaar/cathedral-bazaar/ar01s04.html}): Whenever enough integrated or a non-trivial changes have summed up, a new version is published. Though this releases might now always mark significant changes, they at least allow to quickly fix bugs and avoid infinite procrastination.

@include ChangeLog.texi

@sp 3

The most recent change log is available at Marlene's website at @url{http://service-technology.org/files/marlene/ChangeLog}.



@c --------------------------------------------------------------------------

@node GNU Free Documentation License
@appendix The GNU Free Documentation License

@include fdl.texi

@bye

